<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Felix Betancourt">
<meta name="dcterms.date" content="2024-05-16">

<title>R-Blog-BlueCognition - Network Analysis on subreddit r/politics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">R-Blog-BlueCognition</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Network Analysis on subreddit r/politics</h1>
            <p class="subtitle lead">Social Network Analysis</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Felix Betancourt </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">May 16, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#network-analysis-on-subreddit-rpolitics" id="toc-network-analysis-on-subreddit-rpolitics" class="nav-link active" data-scroll-target="#network-analysis-on-subreddit-rpolitics">Network Analysis on subreddit r/politics</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="net_image_post.jpg" class="img-fluid"></p>
<section id="network-analysis-on-subreddit-rpolitics" class="level2">
<h2 class="anchored" data-anchor-id="network-analysis-on-subreddit-rpolitics">Network Analysis on subreddit r/politics</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>Social media, including Reddit, serves as a prominent platform for discourse and community engagement. The “Politics” subreddit (r/politics) is a hub for discussions on political matters, attracting users who share news articles and express opinions (Bail, 2016).</p>
<p>In recent years, Reddit discussions have intensified, especially regarding U.S. politics, notably around Joe Biden and Donald Trump. Analyzing user interactions in r/politics offers insight into digital political landscapes (Conover et al., 2013).</p>
<p>This research aims to explore Reddit users’ connections within r/politics, focusing on Biden and Trump discussions. We seek to uncover community formation patterns and influencers through social network analysis. Specifically, we’ll examine users’ connectivity, community emergence, and the relationship between post popularity and user influence.</p>
<p>By addressing these questions, we contribute to understanding political discourse on Reddit and social media’s role in shaping public opinion.</p>
</section>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<ol type="1">
<li><p>How are Reddit users connected in the “Politics” subreddit (r/politics), particularly when it comes to topics related to Biden and Trump?</p></li>
<li><p>Are there different communities (networks) for Biden and Trump?</p></li>
<li><p>How are these group of users connected based on the sentiment of their comments?</p></li>
<li><p>Is there a relationship between Score (net value between upvotes and downvotes) for a post, and how the user is connected to other users?</p></li>
</ol>
</section>
<section id="hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis">Hypothesis</h3>
<p>This research is mainly exploratory, I am not expecting something in particular, so I don’t have an specific hypothesis, except for the research question number 4.</p>
<p>In relation to the fourth research question I can expect that:</p>
<p>H1: an user’s higher score should be highly related to a higher centrality in the network.</p>
</section>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidytext))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(dplyr))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(quanteda))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(quanteda.textplots))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(janitor))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(RCurl))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(data.table))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-wrangling" class="level4">
<h4 class="anchored" data-anchor-id="data-wrangling">Data Wrangling</h4>
<ol type="1">
<li><p>I scraped data from the Politics subreddit (r/politics) on April 2nd 2024 using R (RedditExtractoR package) and saved the objects generated from the scrapping to csv files</p></li>
<li><p>This subreddit has 8.5 million users, so the data can be very extensive, however the package used here (RedditExtractoR) pulled the last 1000 post.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C:/Users/fbeta/OneDrive/Blue Cognition/Blog/R-Blog-BlueCognition/posts/Post 4 - Final Project"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read large CSV file using fread</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>politik1 <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"politics_comments1.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>politik2 <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"politics_comments2.csv"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>politik3 <span class="ot">&lt;-</span> <span class="fu">fread</span>(<span class="st">"politics_comments3.csv"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking the structure of the data sets</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(politik1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 983
Columns: 8
$ V1        &lt;chr&gt; "Supreme Court starts arguments as Biden administration defe…
$ date_utc  &lt;IDate&gt; 2024-03-26, 2024-03-26, 2024-03-26, 2024-03-26, 2024-03-26…
$ timestamp &lt;int&gt; 1711463500, 1711463310, 1711462666, 1711462651, 1711462570, …
$ title     &lt;chr&gt; "Supreme Court starts arguments as Biden administration defe…
$ text      &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "Oral argument i…
$ subreddit &lt;chr&gt; "politics", "politics", "politics", "politics", "politics", …
$ comments  &lt;int&gt; 34, 21, 194, 24, 43, 15, 150, 251, 18, 26, 10, 597, 27, 299,…
$ url       &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bo9ce0/supreme_…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(politik2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 983
Columns: 16
$ V1                    &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1…
$ url                   &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bo9…
$ author                &lt;chr&gt; "Cybertronian1512", "ban_hus", "coasterghost", "…
$ date                  &lt;chr&gt; "3/26/2024", "3/26/2024", "3/26/2024", "3/26/202…
$ timestamp             &lt;int&gt; 1711463500, 1711463310, 1711462666, 1711462651, …
$ title                 &lt;chr&gt; "Supreme Court starts arguments as Biden adminis…
$ text                  &lt;chr&gt; "", "", "", "", "", "", "", "", "", "", "", "Ora…
$ subreddit             &lt;chr&gt; "politics", "politics", "politics", "politics", …
$ score                 &lt;int&gt; 304, 127, 1250, 791, 421, 226, 4033, 4842, 197, …
$ upvotes               &lt;int&gt; 304, 127, 1250, 791, 421, 226, 4033, 4842, 197, …
$ downvotes             &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ up_ratio              &lt;dbl&gt; 0.95, 0.92, 0.95, 0.96, 0.91, 0.91, 0.97, 0.97, …
$ total_awards_received &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ golds                 &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ cross_posts           &lt;int&gt; 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, …
$ comments              &lt;int&gt; 34, 21, 194, 24, 43, 15, 150, 250, 18, 26, 10, 5…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(politik3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 95,879
Columns: 11
$ V1         &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …
$ url        &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bo9ce0/supreme…
$ author     &lt;chr&gt; "AutoModerator", "EmmaLouLove", "ctguy54", "EmmaLouLove", "…
$ date       &lt;chr&gt; "3/26/2024", "3/26/2024", "3/26/2024", "3/26/2024", "3/26/2…
$ timestamp  &lt;int&gt; 1711463501, 1711465125, 1711466287, 1711466455, 1711467091,…
$ score      &lt;int&gt; 1, 79, 41, 13, 19, 13, 7, 6, 3, 4, 1, 4, 2, 5, 5, 1, 1, 28,…
$ upvotes    &lt;int&gt; 1, 79, 41, 13, 19, 13, 7, 6, 3, 4, 1, 4, 2, 5, 5, 1, 1, 28,…
$ downvotes  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ golds      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ comment    &lt;chr&gt; "\r\nAs a reminder, this subreddit [is for civil discussion…
$ comment_id &lt;chr&gt; "1", "2", "2_1", "2_1_1", "2_1_1_1", "2_1_1_1_1", "2_1_1_1_…</code></pre>
</div>
</div>
<p>As we can see the the information in object “politik1” is redundant with the information in “politik2” so I won’t use “politik1” at all. “Politik2” contain information about the title of the post, author, and some numeric information like up/down votes, number of replies to the post. “politik3” contain detailed comments on each post and the hierarchical sequence of comments to each post.</p>
<p>For the purpose of this research we will define the users or authors to posts and comments as the nodes, and edges are defined as comments made in the same post; it does mean that the network will be undirected as I will consider only authors commenting in the same post but I won’t capture the direction of the comment (B is commenting to A post).</p>
<p>Let’s do some data wrangling first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cleaning and wrangling</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>politik_df <span class="ot">&lt;-</span> politik2 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>V1, <span class="sc">-</span>timestamp) <span class="co">#eliminating non-relevant columns</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>politik_df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(politik_df)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>politik_df<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(politik_df<span class="sc">$</span>date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>politik_df2 <span class="ot">&lt;-</span> politik3 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>V1, <span class="sc">-</span>timestamp) <span class="co">#eliminating non-relevant columns</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>politik_df2 <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(politik_df2)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>politik_df2<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(politik_df2<span class="sc">$</span>date, <span class="at">format =</span> <span class="st">"%m/%d/%Y"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at the comments from user “Automoderator”, it is like a Reddit moderator bot reminding rules of the forum, so I’ll delete the rows belonging to AutoModerator”. Also there are few commments where the author was “deleted”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>politik_df2 <span class="ot">&lt;-</span> politik_df2[<span class="sc">-</span>(<span class="fu">which</span>(politik_df2<span class="sc">$</span>author <span class="sc">%in%</span> <span class="st">"AutoModerator"</span>)),]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>politik_df3 <span class="ot">&lt;-</span> politik_df2[<span class="sc">-</span>(<span class="fu">which</span>(politik_df2<span class="sc">$</span>author <span class="sc">%in%</span> <span class="st">"[deleted]"</span>)),]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s see how many nodes (authors/users) we got in this data set:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first I created a count column</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>politik_df3 <span class="ot">&lt;-</span> politik_df3 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">countid =</span> <span class="st">"1"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>politik_df3<span class="sc">$</span>countid <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(politik_df3<span class="sc">$</span>countid)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#How many authors (nodes) we have here?</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(politik_df3<span class="sc">$</span>author))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31554</code></pre>
</div>
</div>
<p>In the data set there are about +31k users/authors (nodes), which is way too much nodes for the purpose of my research, so I’ll select a sample of posts to analyze.</p>
<p>I’ll select the top 1% posts with more comments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first let's see the distribution of number of comments</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>percentiles <span class="ot">&lt;-</span> <span class="fu">quantile</span>(politik_df<span class="sc">$</span>comments, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(percentiles)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   25%    50%    75%    90%    95%    99% 
  20.0   46.0  115.0  338.6  576.2 1439.1 </code></pre>
</div>
</div>
<p>Let’s subset the data set with the top 1% posts in terms of comments and let’s see how many posts we have.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>subset_politik2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(politik_df, comments <span class="sc">&gt;=</span> <span class="dv">1439</span> )</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(subset_politik2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 10
Columns: 14
$ url                   &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bo5…
$ author                &lt;chr&gt; "newsweek", "thenewrepublic", "UWCG", "twenafees…
$ date                  &lt;date&gt; 2024-03-26, 2024-03-26, 2024-03-27, 2024-03-27,…
$ title                 &lt;chr&gt; "Letitia James fires back after Donald Trump's b…
$ text                  &lt;chr&gt; "", "", "", "", "", "", "", "", "", ""
$ subreddit             &lt;chr&gt; "politics", "politics", "politics", "politics", …
$ score                 &lt;int&gt; 12409, 28546, 32935, 25237, 13487, 14411, 17102,…
$ upvotes               &lt;int&gt; 12409, 28546, 32935, 25237, 13487, 14411, 17102,…
$ downvotes             &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ up_ratio              &lt;dbl&gt; 0.92, 0.93, 0.91, 0.93, 0.91, 0.91, 0.91, 0.94, …
$ total_awards_received &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ golds                 &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ cross_posts           &lt;int&gt; 1, 2, 5, 7, 9, 2, 3, 3, 6, 3
$ comments              &lt;int&gt; 1476, 2018, 3564, 2419, 1523, 1677, 2291, 1668, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(subset_politik2<span class="sc">$</span>author))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p>We got a data set with 10 original posts and 10 authors, this is now a more “reasonable” data frame to analyze.</p>
<p>Now I need to identify these post into the “politik_df3” data set which contain all the hierarchical comments network.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>subset_politik3 <span class="ot">&lt;-</span> politik_df3 <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">filter</span>(url <span class="sc">%in%</span> subset_politik2<span class="sc">$</span>url)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co">#let's see the df now </span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(subset_politik3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,902
Columns: 10
$ url        &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bo5tnj/letitia…
$ author     &lt;chr&gt; "OokLeeNooma", "AusToddles", "dancode", "GrafZeppelin127", …
$ date       &lt;date&gt; 2024-03-26, 2024-03-26, 2024-03-26, 2024-03-26, 2024-03-26…
$ score      &lt;int&gt; 5480, 2444, 1054, 871, 792, 414, 212, 31, 2, 3, 8, 26, 3, 3…
$ upvotes    &lt;int&gt; 5480, 2444, 1054, 871, 792, 414, 212, 31, 2, 3, 8, 26, 3, 3…
$ downvotes  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ golds      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ comment    &lt;chr&gt; "\"\"Donald Trump is still facing accountability for his st…
$ comment_id &lt;chr&gt; "2", "2_1", "2_1_1_1", "2_1_1_1_1", "2_1_1_1_1_1", "2_1_1_1…
$ countid    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#how many nodes (authors)?</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(subset_politik3<span class="sc">$</span>author))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3869</code></pre>
</div>
</div>
<p>We got 982 posts but still +3.8k nodes, it is still high number of nodes.</p>
<p>I’ll need a different approach.</p>
<p>I’ll select 2 specific posts with a “median” number of comments. One post will be about Trump and another about Biden, specifically I will filter posts by containing the word “Biden” and “Trump” in the title of the post.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co">#First selecting posts with "Trump" or "Biden" included in the title of the post</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Filtering the titles that contain Trump</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>trump_df <span class="ot">&lt;-</span> politik_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"Trump"</span>, title))</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>trump_df<span class="sc">$</span>candidate <span class="ot">&lt;-</span> <span class="st">"Trump"</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's check the distribution of number of comments</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>percentiles_trump <span class="ot">&lt;-</span> <span class="fu">quantile</span>(trump_df<span class="sc">$</span>comments, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>))</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(percentiles_trump)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    25%     50%     75%     90%     95%     99% 
  30.50   74.00  206.00  575.40 1052.50 2176.34 </code></pre>
</div>
</div>
<p>The median comment for Trump’s post is 74 comments.Therefore I’ll select the post with 74 comments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Trump</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>trump_post <span class="ot">&lt;-</span> <span class="fu">subset</span>(trump_df, comments <span class="sc">==</span> <span class="dv">74</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s select Biden’s post</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>({</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Filtering the titles that contain Biden</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>biden_df <span class="ot">&lt;-</span> politik_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"Biden"</span>, title))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>biden_df<span class="sc">$</span>candidate <span class="ot">&lt;-</span> <span class="st">"Biden"</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's check the distribution of number of comments</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>percentiles_biden <span class="ot">&lt;-</span> <span class="fu">quantile</span>(biden_df<span class="sc">$</span>comments, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.50</span>, <span class="fl">0.75</span>, <span class="fl">0.90</span>, <span class="fl">0.95</span>, <span class="fl">0.99</span>))</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(percentiles_biden)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    25%     50%     75%     90%     95%     99% 
  28.00   66.50  171.25  464.50  907.75 1818.00 </code></pre>
</div>
</div>
<p>Median is 66.5 comments, let’s use the post with 67 comments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Biden</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>biden_post <span class="ot">&lt;-</span> <span class="fu">subset</span>(biden_df, comments <span class="sc">==</span> <span class="dv">67</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now I got the 2 main posts, let’s explore a bit those 2 posts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#merging the previous df's</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>trump_biden_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(trump_post, biden_post)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(trump_biden_df<span class="sc">$</span>url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "https://www.reddit.com/r/politics/comments/1bsdho2/us_election_workers_face_thousands_of_threats_so/"
[2] "https://www.reddit.com/r/politics/comments/1bsnq6l/are_black_and_brown_voters_really_fleeing_biden/" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let's identify these posts in the politik3 df (containing all the details)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>subset_politik3 <span class="ot">&lt;-</span> politik_df3 <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">filter</span>(url <span class="sc">%in%</span> trump_biden_df<span class="sc">$</span>url)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co">#creating a new column with the candidate related to the post</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>subset_politik3 <span class="ot">&lt;-</span> subset_politik3 <span class="sc">%&gt;%</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">candidate =</span> <span class="fu">case_when</span>(</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    url <span class="sc">==</span> <span class="st">"https://www.reddit.com/r/politics/comments/1bsdho2/us_election_workers_face_thousands_of_threats_so/"</span> <span class="sc">~</span> <span class="st">"Trump"</span>,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    url <span class="sc">==</span> <span class="st">"https://www.reddit.com/r/politics/comments/1bsnq6l/are_black_and_brown_voters_really_fleeing_biden/"</span> <span class="sc">~</span> <span class="st">"Biden"</span>,</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  ))</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="co">#let's see the df now </span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(subset_politik3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 119
Columns: 11
$ url        &lt;chr&gt; "https://www.reddit.com/r/politics/comments/1bsnq6l/are_bla…
$ author     &lt;chr&gt; "fxkatt", "AngusMcTibbins", "Knoxcore", "Hattopia", "AngusM…
$ date       &lt;date&gt; 2024-03-31, 2024-03-31, 2024-04-01, 2024-03-31, 2024-03-31…
$ score      &lt;int&gt; 20, 27, 3, -18, 23, -12, 18, -3, -14, 9, -7, 5, 2, 1, -4, 1…
$ upvotes    &lt;int&gt; 20, 27, 3, -18, 23, -12, 18, -3, -14, 9, -7, 5, 2, 1, -4, 1…
$ downvotes  &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ golds      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ comment    &lt;chr&gt; "It's very possible that both Biden and Trump are losing so…
$ comment_id &lt;chr&gt; "2", "3", "3_1", "3_2", "3_2_1", "3_2_1_1", "3_2_1_1_1", "3…
$ countid    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ candidate  &lt;chr&gt; "Biden", "Biden", "Biden", "Biden", "Biden", "Biden", "Bide…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's keep only the relevant columns</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>politik_final <span class="ot">&lt;-</span> <span class="fu">select</span>(subset_politik3, <span class="fu">c</span>(<span class="st">"url"</span>, <span class="st">"author"</span>, <span class="st">"score"</span>, <span class="st">"comment"</span>, <span class="st">"comment_id"</span>, <span class="st">"candidate"</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the levels of each comment and its hierarchy</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>politik_final2 <span class="ot">&lt;-</span> politik_final <span class="sc">%&gt;%</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Level =</span> <span class="fu">str_count</span>(comment_id, <span class="at">pattern =</span> <span class="st">"_"</span>) <span class="sc">+</span> <span class="dv">1</span>,  <span class="co"># Count underscores to determine depth</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">ParentID =</span> <span class="fu">ifelse</span>(Level <span class="sc">&gt;</span> <span class="dv">1</span>, <span class="fu">sapply</span>(<span class="fu">strsplit</span>(comment_id, <span class="st">"_"</span>), <span class="cf">function</span>(x) <span class="fu">paste</span>(x[<span class="sc">-</span><span class="fu">length</span>(x)], <span class="at">collapse =</span> <span class="st">"_"</span>)), <span class="cn">NA</span>))</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(politik_final2<span class="sc">$</span>author))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 80</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(politik_final2<span class="sc">$</span>url))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Now we got 80 nodes (authors) from the 2 posts.</p>
</section>
<section id="analysis" class="level4">
<h4 class="anchored" data-anchor-id="analysis">Analysis</h4>
<p>Before proceeding with the network analysis, let’s explore a bit about the authors (users).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let's create some tables to see frequencies and totals</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co">#first I created a count column</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>politik_final2 <span class="ot">&lt;-</span> politik_final2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">countid =</span> <span class="st">"1"</span>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>politik_final2<span class="sc">$</span>countid <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(politik_final2<span class="sc">$</span>countid)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co">#preparing tables</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>politik_table2 <span class="ot">&lt;-</span> <span class="fu">data.table</span>(politik_final2)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="co">#total posts grouped by author</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>count_table2 <span class="ot">&lt;-</span> politik_table2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(author) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Total_posts =</span> <span class="fu">sum</span>(countid))</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>count_table2 <span class="ot">&lt;-</span> count_table2 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_posts))</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(count_table2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 2
   author            Total_posts
   &lt;chr&gt;                   &lt;dbl&gt;
 1 BrtFrkwr                    7
 2 betterwoke                  5
 3 Hattopia                    4
 4 TheBodyPolitic1             4
 5 TheRandomInteger            4
 6 AngusMcTibbins              3
 7 Due-Shirt616                3
 8 NoDesinformatziya           3
 9 TheReddestOrange            3
10 DarkwingDuckHunt            2
# ℹ 70 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>summary_votes <span class="ot">&lt;-</span> politik_table2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(author) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">Total_Score =</span> <span class="fu">sum</span>(score))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>summary_votes <span class="ot">&lt;-</span> summary_votes <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Total_Score))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_votes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 2
   author             Total_Score
   &lt;chr&gt;                    &lt;int&gt;
 1 r-m-russell                 76
 2 AngusMcTibbins              68
 3 OverlyComplexPants          40
 4 BrtFrkwr                    33
 5 betterwoke                  28
 6 TheBodyPolitic1             24
 7 penis_berry_crunch          22
 8 Due-Shirt616                21
 9 NoDesinformatziya           20
10 YeaterdaysQuim              20
# ℹ 70 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Score as a proportion of comments</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>summary_score_ratio <span class="ot">&lt;-</span> politik_table2 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(author) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">Ratio_score_per_comment =</span> <span class="fu">sum</span>(score)<span class="sc">/</span><span class="fu">sum</span>(countid))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>summary_score_ratio <span class="ot">&lt;-</span> summary_score_ratio <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Ratio_score_per_comment))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_score_ratio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 2
   author             Ratio_score_per_comment
   &lt;chr&gt;                                &lt;dbl&gt;
 1 r-m-russell                           76  
 2 OverlyComplexPants                    40  
 3 AngusMcTibbins                        22.7
 4 penis_berry_crunch                    22  
 5 YeaterdaysQuim                        20  
 6 fxkatt                                20  
 7 grixorbatz                            17  
 8 Sea_Engine4333                        16  
 9 Quiet_Dimensions                      14  
10 hdiggyh                               14  
# ℹ 70 more rows</code></pre>
</div>
</div>
<p>I would expect that nodes (users) with higher score and/or higher score per comment should be predominant (central) in the network.</p>
<p>For instance we got the following users in the top 5 in terms of score: “r-m-russell”, “AngusMcTibbins”, “OverlyComplexPants”, “BrtFrkwr” and “betterwoke”.</p>
<p>On the other hand here the top 5 users with highest score per comment: “r-m-russell”, “OverlyComplexPants”, “AngusMcTibbins”, “penis_berry_crunch”, and “YeaterdaysQuim”.</p>
<p>Now I am ready to work on this data set for the Network analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Rename level column as it represent more how deep/far is the comment</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co">#from the initial post, we will use this later as an attribute</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>politik_final2 <span class="ot">&lt;-</span> politik_final2 <span class="sc">%&gt;%</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">distance =</span> Level)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a><span class="co">#identify who is commenting on the same post</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>politik_final2 <span class="ot">&lt;-</span> politik_final2 <span class="sc">%&gt;%</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level =</span> <span class="fu">substr</span>(comment_id, <span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>politik_final2<span class="sc">$</span>level <span class="ot">&lt;-</span> <span class="fu">str_replace_all</span>(politik_final2<span class="sc">$</span>level, <span class="st">"_"</span>, <span class="st">""</span>)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>politik_final2 <span class="ot">&lt;-</span> politik_final2 <span class="sc">%&gt;%</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">level2 =</span> <span class="fu">substr</span>(candidate, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>politik_final2<span class="sc">$</span>comment_id2 <span class="ot">&lt;-</span> <span class="fu">paste</span>(politik_final2<span class="sc">$</span>level2, politik_final2<span class="sc">$</span>level, <span class="at">sep =</span> <span class="st">"_"</span>)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Now I'll create a new object by keeping only the columns I need</span></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>politik_final3 <span class="ot">&lt;-</span> <span class="fu">select</span>(politik_final2, <span class="fu">c</span>(<span class="sc">-</span><span class="st">"comment_id"</span>, <span class="sc">-</span><span class="st">"ParentID"</span>, <span class="sc">-</span><span class="st">"level"</span>, <span class="sc">-</span><span class="st">"level2"</span>))</span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a><span class="co">#Will create a attribute only object to use later</span></span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>politik_attributes <span class="ot">&lt;-</span> <span class="fu">select</span>(politik_final3, <span class="fu">c</span>(<span class="st">"score"</span>, <span class="st">"candidate"</span>, <span class="st">"distance"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I’ll prepare the adjacency matrix:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>politik_m <span class="ot">&lt;-</span> <span class="fu">select</span>(politik_final3, <span class="fu">c</span>(<span class="st">"comment_id2"</span>, <span class="st">"author"</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify unique names and codes</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>unique_names <span class="ot">&lt;-</span> <span class="fu">unique</span>(politik_final3<span class="sc">$</span>author)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>unique_codes <span class="ot">&lt;-</span> <span class="fu">unique</span>(politik_final3<span class="sc">$</span>comment_id2)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create an empty adjacency matrix</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>adj_matrix <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> <span class="fu">length</span>(unique_names), <span class="at">ncol =</span> <span class="fu">length</span>(unique_names),</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>                     <span class="at">dimnames =</span> <span class="fu">list</span>(unique_names, unique_names))</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Populate the adjacency matrix based on shared codes</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(unique_names)) {</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(unique_names)) {</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if names i and j have the same code</span></span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>    shared_code <span class="ot">&lt;-</span> <span class="fu">intersect</span>(politik_final3<span class="sc">$</span>comment_id2[politik_final3<span class="sc">$</span>author <span class="sc">==</span> unique_names[i]],</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>                             politik_final3<span class="sc">$</span>comment_id2[politik_final3<span class="sc">$</span>author <span class="sc">==</span> unique_names[j]])</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(shared_code) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>      adj_matrix[unique_names[i], unique_names[j]] <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># Set relationship to 1</span></span>
<span id="cb45-19"><a href="#cb45-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb45-20"><a href="#cb45-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb45-21"><a href="#cb45-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-22"><a href="#cb45-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-23"><a href="#cb45-23" aria-hidden="true" tabindex="-1"></a><span class="co"># I'll eliminate loops in advance</span></span>
<span id="cb45-24"><a href="#cb45-24" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(adj_matrix) <span class="ot">&lt;-</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="network-analysis" class="level5">
<h5 class="anchored" data-anchor-id="network-analysis">Network Analysis</h5>
<p>Now let’s explore the Network.</p>
<p>It is important to mention that in this research we will assume an undirected network. We are only considering comments within the same post, not specific “direction” of each comment among users.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load packages</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(network))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sna)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(statnet)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>politik.n <span class="ot">&lt;-</span> <span class="fu">network</span>(adj_matrix, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>politik.n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Network attributes:
  vertices = 80 
  directed = FALSE 
  hyper = FALSE 
  loops = FALSE 
  multiple = FALSE 
  bipartite = FALSE 
  total edges= 158 
    missing edges= 0 
    non-missing edges= 158 

 Vertex attribute names: 
    vertex.names 

No edge attributes</code></pre>
</div>
</div>
<p>We got 80 nodes and 316 edges.</p>
<p>Let’s explore the network. I’ll calculate the census for Dyads and triads:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Dyads and Triads census</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>sna<span class="sc">::</span><span class="fu">dyad.census</span>(politik.n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Mut Asym Null
[1,] 158    0 3002</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(sna<span class="sc">::</span><span class="fu">triad.census</span>(politik.n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 82160</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>sna<span class="sc">::</span><span class="fu">triad.census</span>(politik.n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       003 012   102 021D 021U 021C 111D 111U 030T 030C 201 120D 120U 120C 210
[1,] 70689   0 10955    0    0    0    0    0    0    0 179    0    0    0   0
     300
[1,] 337</code></pre>
</div>
</div>
<p>In terms of Dyads, we got 158 mutual connections and 3002 null connections.</p>
<p>In terms of Triads, we got 82160 triads in total: about 70k null triads, 11k open triads (one connection exist), 179 where 2 connections exist, and 337 closed triads.</p>
<p>It seems a disperse network, but let’s see Transitivity and Density:</p>
<p>Let’s check the Transitivity coefficient</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#transitivity</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gtrans</span>(politik.n, <span class="at">mode=</span><span class="st">"graph"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8495798</code></pre>
</div>
</div>
<p>The transitivity coefficient is 0.85 which indicates a high level of cohesion.</p>
<p>Let’s see the density:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get network density: statnet</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>network<span class="sc">::</span><span class="fu">network.density</span>(politik.n) <span class="co">#already exclude loops</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05</code></pre>
</div>
</div>
<p>This density of 0.05 indicates a relatively sparse network with few connections between nodes.</p>
<p>This combination of high transitivity and low density might suggests the presence of strong community structure in the network, where nodes are densely connected within their respective communities but sparsely connected between communities.</p>
<p>Let’s visualize the network</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the network</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(politik.n, <span class="at">displaylabels =</span> <span class="cn">TRUE</span>, <span class="at">label.cex=</span><span class="fl">0.7</span>, <span class="at">vertex.cex=</span><span class="fl">1.5</span>, <span class="at">displayisolates=</span>T, <span class="at">main =</span> <span class="st">"Authors Network"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Without isolated nodes and labels</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the network</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(politik.n, <span class="at">displaylabels =</span> F, <span class="at">label.cex=</span><span class="fl">0.7</span>, <span class="at">vertex.cex=</span><span class="fl">1.5</span>, <span class="at">displayisolates=</span>F, <span class="at">main =</span> <span class="st">"Authors Network"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s now include the Candidate as attribute. We will clasify the users as per their comments to Biden or Trump posts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll create a column with Biden true-false attribute</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>politik_final3at <span class="ot">&lt;-</span> politik_final3 <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">biden =</span> <span class="fu">if_else</span>(candidate <span class="sc">==</span> <span class="st">"Biden"</span>, <span class="st">"TRUE"</span>, <span class="st">"FALSE"</span>)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="co">#now let's see how authonrs in Biden and Trump are interacting</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>nodeColors<span class="ot">&lt;-</span><span class="fu">ifelse</span>(politik_final3at<span class="sc">$</span>biden,<span class="st">"dodgerblue"</span>,<span class="st">"red"</span>)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(politik.n,<span class="at">displaylabels=</span>F,<span class="at">vertex.col=</span>nodeColors,<span class="at">vertex.cex=</span><span class="fl">1.2</span>, <span class="at">displayisolates=</span>T, <span class="at">main =</span> <span class="st">"Authors Network by Candidate"</span>) <span class="co">#including isolated nodes</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Biden"</span>, <span class="st">"Trump"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"dodgerblue"</span>, <span class="st">"red"</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">21</span>), <span class="at">title =</span> <span class="st">"Node Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Let’s exclude isolated nodes</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(politik.n,<span class="at">displaylabels=</span>F,<span class="at">vertex.col=</span>nodeColors,<span class="at">vertex.cex=</span><span class="fl">1.2</span>, <span class="at">displayisolates=</span>F, <span class="at">main =</span> <span class="st">"Authors Network by Candidate (excluding isolated nodes)"</span>) <span class="co">#excluding isolated nodes</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Biden"</span>, <span class="st">"Trump"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"dodgerblue"</span>, <span class="st">"red"</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">21</span>), <span class="at">title =</span> <span class="st">"Node Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It looks like there are closed communities not connected among them. Which is consistent with the Transitivity vs Density finding before.</p>
<p>In particular Biden’s commentors tend to be together and Trump’s commentors seems more disperse.</p>
<p>Let’s see who are the authors with highest degree centrality</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a dataset of vertex names and degree: statnet</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>politik.nodes.df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> politik.n <span class="sc">%v%</span> <span class="st">"vertex.names"</span>,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">degree =</span> sna<span class="sc">::</span><span class="fu">degree</span>(politik.n))</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>politik_table7 <span class="ot">&lt;-</span> <span class="fu">data.table</span>(politik.nodes.df)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="co">#order by centrality degree</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>politik_table7 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(degree)) <span class="sc">%&gt;%</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  name degree
                &lt;char&gt;  &lt;num&gt;
 1:           Knoxcore     30
 2:  NoDesinformatziya     30
 3:           BrtFrkwr     28
 4:   TheRandomInteger     26
 5:    TheBodyPolitic1     20
 6:         Fasefirst2     20
 7:           cdiddy19     20
 8: Invincible_auxcord     20
 9:     Bulky-You-5657     20
10:        nickmiele22     20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(politik_table7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     name               degree    
 Length:80          Min.   : 0.0  
 Class :character   1st Qu.: 0.0  
 Mode  :character   Median : 6.0  
                    Mean   : 7.9  
                    3rd Qu.:14.5  
                    Max.   :30.0  </code></pre>
</div>
</div>
<p>Let’s explore the correlation between centrality degree and score (remember it is the net value between upvotes and downvotes).</p>
<p>I am expecting a significant positive relationship between soore and degree centrality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(igraph))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the igraph object</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>politik.ig <span class="ot">&lt;-</span> <span class="fu">graph_from_adjacency_matrix</span>(adj_matrix, <span class="at">mode =</span> <span class="st">"undirected"</span>)  <span class="co"># Undirected by default</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate degree centrality for each node</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>degree_centrality <span class="ot">&lt;-</span> <span class="fu">degree</span>(politik.ig, <span class="at">mode =</span> <span class="st">"all"</span>)</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a><span class="co"># If nodes do not have names, you can use node IDs</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.null</span>(<span class="fu">V</span>(politik.ig)<span class="sc">$</span>name)) {</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">V</span>(politik.ig)<span class="sc">$</span>name <span class="ot">&lt;-</span> <span class="fu">as.character</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">vcount</span>(politik.ig))</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Check node names</span></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>node_names <span class="ot">&lt;-</span> <span class="fu">V</span>(politik.ig)<span class="sc">$</span>name</span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a sample data frame with some values for each node</span></span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure the data frame has the same node identifiers as the graph</span></span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">author =</span> node_names,  <span class="co"># Node names or IDs</span></span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> <span class="fu">runif</span>(<span class="fu">vcount</span>(politik.ig), <span class="dv">1</span>, <span class="dv">100</span>)  <span class="co"># Random values between 1 and 100</span></span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert degree centrality to a data frame</span></span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a>degree_centrality_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">author =</span> node_names,  <span class="co"># Node names or IDs</span></span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">degree_centrality =</span> degree_centrality  <span class="co"># Degree centrality values</span></span>
<span id="cb66-28"><a href="#cb66-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-29"><a href="#cb66-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-30"><a href="#cb66-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the degree centrality data frame with the existing data frame</span></span>
<span id="cb66-31"><a href="#cb66-31" aria-hidden="true" tabindex="-1"></a>merged_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(df, degree_centrality_df, <span class="at">by =</span> <span class="st">"author"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb66-32"><a href="#cb66-32" aria-hidden="true" tabindex="-1"></a>merged_df2 <span class="ot">&lt;-</span> <span class="fu">merge</span>(merged_df, politik_final2, <span class="at">by =</span> <span class="st">"author"</span>, <span class="at">all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb66-33"><a href="#cb66-33" aria-hidden="true" tabindex="-1"></a>degree_scoredf <span class="ot">&lt;-</span> <span class="fu">select</span>(merged_df2, <span class="fu">c</span>(<span class="st">"degree_centrality"</span>, <span class="st">"score"</span>))</span>
<span id="cb66-34"><a href="#cb66-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-35"><a href="#cb66-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the correlation coefficient between 'score' and 'degree_centrality'</span></span>
<span id="cb66-36"><a href="#cb66-36" aria-hidden="true" tabindex="-1"></a>cor_matrix1 <span class="ot">&lt;-</span> <span class="fu">cor</span>(degree_scoredf, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb66-37"><a href="#cb66-37" aria-hidden="true" tabindex="-1"></a>cor_matrix1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  degree_centrality       score
degree_centrality       1.000000000 0.001921923
score                   0.001921923 1.000000000</code></pre>
</div>
</div>
<p>Seems that the relationship between score and degree centrality is very low (0.002).</p>
<p>So I can’t accept my hypothesis.</p>
<p>I am curious about the top 5 users with higher degree centrality.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>degree_scoredf3 <span class="ot">&lt;-</span> <span class="fu">select</span>(merged_df2, <span class="fu">c</span>(<span class="st">"degree_centrality"</span>, <span class="st">"author"</span>))</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">distinct</span>(degree_scoredf3, author, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>subset_df <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(degree_centrality))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   degree_centrality               author
1                 15             Knoxcore
2                 15    NoDesinformatziya
3                 14             BrtFrkwr
4                 13     TheRandomInteger
5                 10       Bulky-You-5657
6                 10             cdiddy19
7                 10  Exciting_Slice_9492
8                 10           Fasefirst2
9                 10        hilljack26301
10                10   Invincible_auxcord
11                10             Kamelasa
12                10          nickmiele22
13                10      TheBodyPolitic1
14                 8   Admirable_Bad_5649
15                 8           betterwoke
16                 8     DarkwingDuckHunt
17                 8          Scarlettail
18                 8        Spara-Extreme
19                 8     TheReddestOrange
20                 8     Thick-Return1694
21                 7          bakeacake45
22                 6            AliMcGraw
23                 6       AngusMcTibbins
24                 6             Hattopia
25                 6    hellocattlecookie
26                 6   Mundane_Rabbit7751
27                 6   OverlyComplexPants
28                 6         Roasted_Butt
29                 6    SeegsonSynthetics
30                 6             Shaunair
31                 4             caserock
32                 4     CecilTWashington
33                 4            gefjunhel
34                 4   penis_berry_crunch
35                 4          r-m-russell
36                 3         Due-Shirt616
37                 3              hdiggyh
38                 3             iuthnj34
39                 3               JeffMo
40                 3        PineTreeBanjo
41                 3              Purify5
42                 3     Quiet_Dimensions
43                 3       YeaterdaysQuim
44                 1  Candid_Chicken_9246
45                 1   FijiFanBotNotGay69
46                 1        Happypappy213
47                 1            hindusoul
48                 1      InGreedWeTrust3
49                 1              LariRed
50                 1   physical_graffitti
51                 1            Tower6011
52                 0              bck1999
53                 0     bloombergopinion
54                 0          cryolongman
55                 0          Donut131313
56                 0              eldred2
57                 0      Empty-Rise-4409
58                 0     fore_skin_walker
59                 0               fxkatt
60                 0           grixorbatz
61                 0            Guttenber
62                 0        HonoredPeople
63                 0     ImportantNeck491
64                 0        inconsistent3
65                 0       JubalHarshaw23
66                 0             njman100
67                 0          No_Yak_6227
68                 0       Odd_Tiger_2278
69                 0 platanthera_ciliaris
70                 0        PoopieButt317
71                 0  Practical_Shop_4055
72                 0         RUIN_NATION_
73                 0       Sea_Engine4333
74                 0          SeaSuch2077
75                 0             spotspam
76                 0          stjoechief1
77                 0          StormOk7544
78                 0              syg-123
79                 0               th1961
80                 0         Willowgirl78</code></pre>
</div>
</div>
<p>Users with higher degree centrality are “Knoxcore”, “NoDesinformatziya”, “BrtFrkwr”, “TheRandomInteger”, and “Bulky-You-5657”</p>
<p>Out of these 5 nodes only one of them (“BrtFrkwr”) is also in the top 5 related to score. So it is consistent with the low correlation between score and centrality.</p>
<p>Let’s now check what clusters (communities) we do have in this network.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># run clustering algorithm: fast_greedy</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>politik.fg <span class="ot">&lt;-</span> igraph<span class="sc">::</span><span class="fu">cluster_fast_greedy</span>(politik.ig)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co"># inspect clustering object</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>politik.fg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>IGRAPH clustering fast greedy, groups: 37, mod: 0.63
+ groups:
  $`1`
   [1] "AngusMcTibbins"      "Knoxcore"            "Hattopia"           
   [4] "Mundane_Rabbit7751"  "NoDesinformatziya"   "SeegsonSynthetics"  
   [7] "hellocattlecookie"   "TheBodyPolitic1"     "Fasefirst2"         
  [10] "cdiddy19"            "Invincible_auxcord"  "Bulky-You-5657"     
  [13] "nickmiele22"         "Exciting_Slice_9492" "hilljack26301"      
  [16] "Kamelasa"           
  
  $`2`
   [1] "OverlyComplexPants"  "AliMcGraw"           "bakeacake45"        
  + ... omitted several groups/vertices</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>igraph<span class="sc">::</span><span class="fu">groups</span>(politik.fg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`1`
 [1] "AngusMcTibbins"      "Knoxcore"            "Hattopia"           
 [4] "Mundane_Rabbit7751"  "NoDesinformatziya"   "SeegsonSynthetics"  
 [7] "hellocattlecookie"   "TheBodyPolitic1"     "Fasefirst2"         
[10] "cdiddy19"            "Invincible_auxcord"  "Bulky-You-5657"     
[13] "nickmiele22"         "Exciting_Slice_9492" "hilljack26301"      
[16] "Kamelasa"           

$`2`
 [1] "OverlyComplexPants"  "AliMcGraw"           "bakeacake45"        
 [4] "Roasted_Butt"        "BrtFrkwr"            "TheRandomInteger"   
 [7] "Shaunair"            "betterwoke"          "DarkwingDuckHunt"   
[10] "Thick-Return1694"    "Spara-Extreme"       "Admirable_Bad_5649" 
[13] "TheReddestOrange"    "Scarlettail"         "Tower6011"          
[16] "Candid_Chicken_9246"

$`3`
[1] "r-m-russell"        "penis_berry_crunch" "CecilTWashington"  
[4] "caserock"           "gefjunhel"         

$`4`
[1] "iuthnj34"       "YeaterdaysQuim" "hdiggyh"        "Purify5"       

$`5`
[1] "Quiet_Dimensions" "Due-Shirt616"     "JeffMo"           "PineTreeBanjo"   

$`6`
[1] "physical_graffitti" "hindusoul"         

$`7`
[1] "LariRed"         "InGreedWeTrust3"

$`8`
[1] "Happypappy213"      "FijiFanBotNotGay69"

$`9`
[1] "fxkatt"

$`10`
[1] "Sea_Engine4333"

$`11`
[1] "Practical_Shop_4055"

$`12`
[1] "PoopieButt317"

$`13`
[1] "inconsistent3"

$`14`
[1] "Empty-Rise-4409"

$`15`
[1] "stjoechief1"

$`16`
[1] "th1961"

$`17`
[1] "platanthera_ciliaris"

$`18`
[1] "No_Yak_6227"

$`19`
[1] "fore_skin_walker"

$`20`
[1] "HonoredPeople"

$`21`
[1] "bloombergopinion"

$`22`
[1] "RUIN_NATION_"

$`23`
[1] "ImportantNeck491"

$`24`
[1] "grixorbatz"

$`25`
[1] "spotspam"

$`26`
[1] "JubalHarshaw23"

$`27`
[1] "StormOk7544"

$`28`
[1] "njman100"

$`29`
[1] "Odd_Tiger_2278"

$`30`
[1] "cryolongman"

$`31`
[1] "Willowgirl78"

$`32`
[1] "Guttenber"

$`33`
[1] "SeaSuch2077"

$`34`
[1] "syg-123"

$`35`
[1] "bck1999"

$`36`
[1] "Donut131313"

$`37`
[1] "eldred2"</code></pre>
</div>
</div>
<p>There are 2 main clusters in the network.</p>
<p>Let’s see the density of each cluster using block model function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">blockmodel</span>(politik.n, politik.fg<span class="sc">$</span>membership)<span class="sc">$</span>block.model,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Block 1 Block 2 Block 3 Block 4 Block 5 Block 6 Block 7 Block 8
Block 1     0.62    0.00       0       0       0       0       0       0
Block 2     0.00    0.48       0       0       0       0       0       0
Block 3     0.00    0.00       1       0       0       0       0       0
Block 4     0.00    0.00       0       1       0       0       0       0
Block 5     0.00    0.00       0       0       1       0       0       0
Block 6     0.00    0.00       0       0       0       1       0       0
Block 7     0.00    0.00       0       0       0       0       1       0
Block 8     0.00    0.00       0       0       0       0       0       1
Block 9     0.00    0.00       0       0       0       0       0       0
Block 10    0.00    0.00       0       0       0       0       0       0
Block 11    0.00    0.00       0       0       0       0       0       0
Block 12    0.00    0.00       0       0       0       0       0       0
Block 13    0.00    0.00       0       0       0       0       0       0
Block 14    0.00    0.00       0       0       0       0       0       0
Block 15    0.00    0.00       0       0       0       0       0       0
Block 16    0.00    0.00       0       0       0       0       0       0
Block 17    0.00    0.00       0       0       0       0       0       0
Block 18    0.00    0.00       0       0       0       0       0       0
Block 19    0.00    0.00       0       0       0       0       0       0
Block 20    0.00    0.00       0       0       0       0       0       0
Block 21    0.00    0.00       0       0       0       0       0       0
Block 22    0.00    0.00       0       0       0       0       0       0
Block 23    0.00    0.00       0       0       0       0       0       0
Block 24    0.00    0.00       0       0       0       0       0       0
Block 25    0.00    0.00       0       0       0       0       0       0
Block 26    0.00    0.00       0       0       0       0       0       0
Block 27    0.00    0.00       0       0       0       0       0       0
Block 28    0.00    0.00       0       0       0       0       0       0
Block 29    0.00    0.00       0       0       0       0       0       0
Block 30    0.00    0.00       0       0       0       0       0       0
Block 31    0.00    0.00       0       0       0       0       0       0
Block 32    0.00    0.00       0       0       0       0       0       0
Block 33    0.00    0.00       0       0       0       0       0       0
Block 34    0.00    0.00       0       0       0       0       0       0
Block 35    0.00    0.00       0       0       0       0       0       0
Block 36    0.00    0.00       0       0       0       0       0       0
Block 37    0.00    0.00       0       0       0       0       0       0
         Block 9 Block 10 Block 11 Block 12 Block 13 Block 14 Block 15 Block 16
Block 1        0        0        0        0        0        0        0        0
Block 2        0        0        0        0        0        0        0        0
Block 3        0        0        0        0        0        0        0        0
Block 4        0        0        0        0        0        0        0        0
Block 5        0        0        0        0        0        0        0        0
Block 6        0        0        0        0        0        0        0        0
Block 7        0        0        0        0        0        0        0        0
Block 8        0        0        0        0        0        0        0        0
Block 9      NaN        0        0        0        0        0        0        0
Block 10       0      NaN        0        0        0        0        0        0
Block 11       0        0      NaN        0        0        0        0        0
Block 12       0        0        0      NaN        0        0        0        0
Block 13       0        0        0        0      NaN        0        0        0
Block 14       0        0        0        0        0      NaN        0        0
Block 15       0        0        0        0        0        0      NaN        0
Block 16       0        0        0        0        0        0        0      NaN
Block 17       0        0        0        0        0        0        0        0
Block 18       0        0        0        0        0        0        0        0
Block 19       0        0        0        0        0        0        0        0
Block 20       0        0        0        0        0        0        0        0
Block 21       0        0        0        0        0        0        0        0
Block 22       0        0        0        0        0        0        0        0
Block 23       0        0        0        0        0        0        0        0
Block 24       0        0        0        0        0        0        0        0
Block 25       0        0        0        0        0        0        0        0
Block 26       0        0        0        0        0        0        0        0
Block 27       0        0        0        0        0        0        0        0
Block 28       0        0        0        0        0        0        0        0
Block 29       0        0        0        0        0        0        0        0
Block 30       0        0        0        0        0        0        0        0
Block 31       0        0        0        0        0        0        0        0
Block 32       0        0        0        0        0        0        0        0
Block 33       0        0        0        0        0        0        0        0
Block 34       0        0        0        0        0        0        0        0
Block 35       0        0        0        0        0        0        0        0
Block 36       0        0        0        0        0        0        0        0
Block 37       0        0        0        0        0        0        0        0
         Block 17 Block 18 Block 19 Block 20 Block 21 Block 22 Block 23
Block 1         0        0        0        0        0        0        0
Block 2         0        0        0        0        0        0        0
Block 3         0        0        0        0        0        0        0
Block 4         0        0        0        0        0        0        0
Block 5         0        0        0        0        0        0        0
Block 6         0        0        0        0        0        0        0
Block 7         0        0        0        0        0        0        0
Block 8         0        0        0        0        0        0        0
Block 9         0        0        0        0        0        0        0
Block 10        0        0        0        0        0        0        0
Block 11        0        0        0        0        0        0        0
Block 12        0        0        0        0        0        0        0
Block 13        0        0        0        0        0        0        0
Block 14        0        0        0        0        0        0        0
Block 15        0        0        0        0        0        0        0
Block 16        0        0        0        0        0        0        0
Block 17      NaN        0        0        0        0        0        0
Block 18        0      NaN        0        0        0        0        0
Block 19        0        0      NaN        0        0        0        0
Block 20        0        0        0      NaN        0        0        0
Block 21        0        0        0        0      NaN        0        0
Block 22        0        0        0        0        0      NaN        0
Block 23        0        0        0        0        0        0      NaN
Block 24        0        0        0        0        0        0        0
Block 25        0        0        0        0        0        0        0
Block 26        0        0        0        0        0        0        0
Block 27        0        0        0        0        0        0        0
Block 28        0        0        0        0        0        0        0
Block 29        0        0        0        0        0        0        0
Block 30        0        0        0        0        0        0        0
Block 31        0        0        0        0        0        0        0
Block 32        0        0        0        0        0        0        0
Block 33        0        0        0        0        0        0        0
Block 34        0        0        0        0        0        0        0
Block 35        0        0        0        0        0        0        0
Block 36        0        0        0        0        0        0        0
Block 37        0        0        0        0        0        0        0
         Block 24 Block 25 Block 26 Block 27 Block 28 Block 29 Block 30
Block 1         0        0        0        0        0        0        0
Block 2         0        0        0        0        0        0        0
Block 3         0        0        0        0        0        0        0
Block 4         0        0        0        0        0        0        0
Block 5         0        0        0        0        0        0        0
Block 6         0        0        0        0        0        0        0
Block 7         0        0        0        0        0        0        0
Block 8         0        0        0        0        0        0        0
Block 9         0        0        0        0        0        0        0
Block 10        0        0        0        0        0        0        0
Block 11        0        0        0        0        0        0        0
Block 12        0        0        0        0        0        0        0
Block 13        0        0        0        0        0        0        0
Block 14        0        0        0        0        0        0        0
Block 15        0        0        0        0        0        0        0
Block 16        0        0        0        0        0        0        0
Block 17        0        0        0        0        0        0        0
Block 18        0        0        0        0        0        0        0
Block 19        0        0        0        0        0        0        0
Block 20        0        0        0        0        0        0        0
Block 21        0        0        0        0        0        0        0
Block 22        0        0        0        0        0        0        0
Block 23        0        0        0        0        0        0        0
Block 24      NaN        0        0        0        0        0        0
Block 25        0      NaN        0        0        0        0        0
Block 26        0        0      NaN        0        0        0        0
Block 27        0        0        0      NaN        0        0        0
Block 28        0        0        0        0      NaN        0        0
Block 29        0        0        0        0        0      NaN        0
Block 30        0        0        0        0        0        0      NaN
Block 31        0        0        0        0        0        0        0
Block 32        0        0        0        0        0        0        0
Block 33        0        0        0        0        0        0        0
Block 34        0        0        0        0        0        0        0
Block 35        0        0        0        0        0        0        0
Block 36        0        0        0        0        0        0        0
Block 37        0        0        0        0        0        0        0
         Block 31 Block 32 Block 33 Block 34 Block 35 Block 36 Block 37
Block 1         0        0        0        0        0        0        0
Block 2         0        0        0        0        0        0        0
Block 3         0        0        0        0        0        0        0
Block 4         0        0        0        0        0        0        0
Block 5         0        0        0        0        0        0        0
Block 6         0        0        0        0        0        0        0
Block 7         0        0        0        0        0        0        0
Block 8         0        0        0        0        0        0        0
Block 9         0        0        0        0        0        0        0
Block 10        0        0        0        0        0        0        0
Block 11        0        0        0        0        0        0        0
Block 12        0        0        0        0        0        0        0
Block 13        0        0        0        0        0        0        0
Block 14        0        0        0        0        0        0        0
Block 15        0        0        0        0        0        0        0
Block 16        0        0        0        0        0        0        0
Block 17        0        0        0        0        0        0        0
Block 18        0        0        0        0        0        0        0
Block 19        0        0        0        0        0        0        0
Block 20        0        0        0        0        0        0        0
Block 21        0        0        0        0        0        0        0
Block 22        0        0        0        0        0        0        0
Block 23        0        0        0        0        0        0        0
Block 24        0        0        0        0        0        0        0
Block 25        0        0        0        0        0        0        0
Block 26        0        0        0        0        0        0        0
Block 27        0        0        0        0        0        0        0
Block 28        0        0        0        0        0        0        0
Block 29        0        0        0        0        0        0        0
Block 30        0        0        0        0        0        0        0
Block 31      NaN        0        0        0        0        0        0
Block 32        0      NaN        0        0        0        0        0
Block 33        0        0      NaN        0        0        0        0
Block 34        0        0        0      NaN        0        0        0
Block 35        0        0        0        0      NaN        0        0
Block 36        0        0        0        0        0      NaN        0
Block 37        0        0        0        0        0        0      NaN</code></pre>
</div>
</div>
<p>The blocks 1 and 2 in our network seems dense.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>df_comm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Node =</span> <span class="fu">V</span>(politik.ig)<span class="sc">$</span>name,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Community =</span> politik.fg<span class="sc">$</span>membership,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Degree =</span> degree_centrality</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Find maximum degree for each community</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>highest_degree_nodes <span class="ot">&lt;-</span> df_comm <span class="sc">%&gt;%</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Community) <span class="sc">%&gt;%</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Degree <span class="sc">==</span> <span class="fu">max</span>(Degree)) <span class="sc">%&gt;%</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>highest_degree_nodes <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="sc">-</span><span class="fu">desc</span>(Community))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 51 × 3
   Node               Community Degree
   &lt;chr&gt;                  &lt;dbl&gt;  &lt;dbl&gt;
 1 Knoxcore                   1     15
 2 NoDesinformatziya          1     15
 3 BrtFrkwr                   2     14
 4 r-m-russell                3      4
 5 penis_berry_crunch         3      4
 6 CecilTWashington           3      4
 7 caserock                   3      4
 8 gefjunhel                  3      4
 9 iuthnj34                   4      3
10 YeaterdaysQuim             4      3
# ℹ 41 more rows</code></pre>
</div>
</div>
<p>Let’s now visualize the communities including the nodes with highest degree centrality for the main communities (1 and 2):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify nodes with high degree centrality (e.g., top 3)</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>top_nodes <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">sort</span>(degree_centrality, <span class="at">decreasing =</span> <span class="cn">TRUE</span>))[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a custom labeling vector</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>node_labels <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="fu">vcount</span>(politik.ig))</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the labels for the nodes with high degree centrality</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>node_labels[top_nodes] <span class="ot">&lt;-</span> top_nodes</span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify isolated nodes</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>isolated_nodes <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">degree</span>(politik.ig) <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove isolated nodes from the network</span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>network_no_isolated <span class="ot">&lt;-</span> <span class="fu">delete_vertices</span>(politik.ig, isolated_nodes)</span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(network_no_isolated,</span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label =</span> node_labels,  </span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label.cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.color =</span> <span class="fu">membership</span>(politik.fg),</span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.label.color =</span> <span class="st">"black"</span>,</span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">vertex.shape =</span> <span class="st">"sphere"</span>,</span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">layout =</span> layout_with_fr,</span>
<span id="cb78-22"><a href="#cb78-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Communities without isolated nodes and labeling top 5 central nodes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
<p>It looks like while we have 2 main communities the nodes with highest degree centrality are mostly in one of the communities.</p>
<p>It seems like that group of authors are close among them and at the same time are central in the network.</p>
</section>
<section id="sentiment-analysis-and-the-network" class="level5">
<h5 class="anchored" data-anchor-id="sentiment-analysis-and-the-network">Sentiment Analysis and the Network</h5>
<p>Lastly let’s add a new attribute to the network using text analysis, in particular sentiment analysis.</p>
<p>Let’s get the sentiment for each author’s comments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sentimentr)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="co">#labeling based on the sentiment score</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>comments <span class="ot">&lt;-</span> politik_final3<span class="sc">$</span>comment</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>get_sentiment_label <span class="ot">&lt;-</span> <span class="cf">function</span>(ave_sentiment) {</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (ave_sentiment <span class="sc">&gt;</span> <span class="fl">0.1</span>) {</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"Positive"</span>)</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (ave_sentiment <span class="sc">&lt;</span> <span class="sc">-</span><span class="fl">0.1</span>) {</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"Negative"</span>)</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="st">"Neutral"</span>)</span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb79-13"><a href="#cb79-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb79-14"><a href="#cb79-14" aria-hidden="true" tabindex="-1"></a>sentiment_scores <span class="ot">&lt;-</span> <span class="fu">sentiment_by</span>(<span class="at">x =</span> comments, <span class="at">text.var =</span> comments)</span>
<span id="cb79-15"><a href="#cb79-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-16"><a href="#cb79-16" aria-hidden="true" tabindex="-1"></a><span class="co">#adding the label for each author in the data set</span></span>
<span id="cb79-17"><a href="#cb79-17" aria-hidden="true" tabindex="-1"></a>politik_final3<span class="sc">$</span>sentiment <span class="ot">&lt;-</span> <span class="fu">sapply</span>(sentiment_scores<span class="sc">$</span>ave_sentiment, get_sentiment_label)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s visualize the network by sentiment of each node.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a graph object from the data frame</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> <span class="fu">graph_from_data_frame</span>(politik.n, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add node attributes to the graph</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g)<span class="sc">$</span>sentiment <span class="ot">&lt;-</span> politik_final3<span class="sc">$</span>sentiment[<span class="fu">match</span>(<span class="fu">V</span>(g)<span class="sc">$</span>name, politik_final3<span class="sc">$</span>author)]</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define color palette for categories</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>color_palette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Negative"</span> <span class="ot">=</span> <span class="st">"red"</span>, <span class="st">"Neutral"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Positive"</span> <span class="ot">=</span> <span class="st">"lightgreen"</span>)</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the network with colored nodes</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(g, <span class="at">vertex.color =</span> color_palette[<span class="fu">V</span>(g)<span class="sc">$</span>sentiment], <span class="at">layout =</span> layout_nicely, <span class="at">vertex.label =</span> <span class="cn">NA</span>, <span class="at">vertex.size =</span> <span class="dv">7</span>, <span class="at">isolates=</span><span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">"Authors Network by Sentiment"</span>)</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Positive"</span>, <span class="st">"Neutral"</span>, <span class="st">"Negative"</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"lightgreen"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>), <span class="at">pch =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">21</span>), <span class="at">title =</span> <span class="st">"Node Sentiment"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this chart it looks like:</p>
<ol type="1">
<li>Most of the sentiments are either neutral or negative</li>
<li>Sentiments tend to get closer, or group among them.</li>
</ol>
</section>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<ol type="1">
<li><p>The network was found to be sparse (low density) but highly interconnected within subgroups (high transitivity), suggesting the presence of distinct communities.</p></li>
<li><p>The visualization of the network confirmed the presence of communities, showing separate clusters of users commenting on Biden and Trump posts. The network was divided into 37 distinct clusters, indicating multiple smaller communities within the larger Biden and Trump-focused groups.</p></li>
<li><p>The hypothesis that users with higher scores (more upvotes or higher score) would also have more central positions in the network was not supported. The correlation between score and centrality was negligible.</p></li>
<li><p>While score wasn’t a strong indicator of influence, degree centrality (number of connections) was used to identify the most connected users. These users may play important roles in shaping discussions within their respective communities.</p></li>
<li><p>In terms of the sentiment analysis it seems that most comments were neutral or negative. And, users with similar sentiments tended to interact with each other.</p></li>
</ol>
<p>This Network Analysis research offers interesting insights into the social dynamics of a politically charged online community. It highlights the presence of distinct communities, the complex interplay between user engagement (score) and influence (centrality), and the opportunity for further exploration of the factors shaping political discourse on platforms like Reddit.</p>
</section>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<p>Bail C. A. (2016). Combining natural language processing and network analysis to examine how advocacy organizations stimulate conversation on social media. Proceedings of the National Academy of Sciences of the United States of America, 113(42), 11823–11828. https://doi.org/10.1073/pnas.1607151113</p>
<p>Conover, M., Ratkiewicz, J., Francisco, M., Goncalves, B., Menczer, F., &amp; Flammini, A. (2021). Political Polarization on Twitter. Proceedings of the International AAAI Conference on Web and Social Media, 5(1), 89-96. https://doi.org/10.1609/icwsm.v5i1.14126</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
          // default icon
          link.classList.add("external");
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>