<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Felix Betancourt">
<meta name="dcterms.date" content="2024-02-01">

<title>R-Blog-BlueCognition - Spotify Songs Streaming Prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">R-Blog-BlueCognition</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Spotify Songs Streaming Prediction</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">spotify</div>
                <div class="quarto-category">machine learning</div>
                <div class="quarto-category">regression</div>
                <div class="quarto-category">classification</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Felix Betancourt </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 1, 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<p><img src="spotify.jpg" class="img-fluid"></p>
<section id="section-1---motivation" class="level1">
<h1>Section 1 - Motivation</h1>
<p>As an avid music listener in general, I have always been curious about the impact of streaming platforms on the music industry in terms of how it has been changing the way people consume, distribute, and monetize music.</p>
<p>The shift from ownership to access has led to a more consumption-based model, democratized access to music, and enhanced music discoverability. Streaming platforms typically pay artists and rights holders based on the number of streams their songs accumulate.</p>
<p>In this context, one of the most important impacts of the streaming platform is on the revenue streams, which have been transformed significantly: <strong>the number of streams is becoming the dominant source of income for many artists.</strong></p>
<p>Streaming platforms generate vast amounts of data on listener behavior, preferences, and trends. This data has become invaluable for artists, labels, and streaming services in understanding audience demographics, optimizing marketing strategies, and identifying opportunities for promotion and monetization.</p>
<p>So, predicting total streams allows stakeholders to forecast. The ability to predict the total number of streams a song can get is crucial for several reasons:</p>
<ol type="1">
<li><p>First, it helps forecast potential revenue streams from a particular track, which is particularly important for budgeting, planning promotional activities, and making financial decisions.</p></li>
<li><p>The total number of streams is a critical metric for evaluating the performance and popularity of a song. By predicting future streams, artists, record labels, and streaming platforms can assess the success of a release and compare it to past performances.</p>
<p>This information is essential for understanding audience preferences and adjusting strategies accordingly.</p></li>
<li><p>Predicting total streams enables targeted marketing and promotional efforts, as it helps identify songs likely to garner high stream counts.</p></li>
<li><p>Finally, streaming platforms often curate playlists based on predicted popularity and user preferences. Predicting total streams helps platforms identify which songs will likely resonate with their users/audience, leading to better playlist curation therefore increased user engagement.</p></li>
</ol>
<p>Overall, the ability to predict total streams for a song provides valuable insights for various stakeholders in the music industry, helping them make informed decisions and optimize their strategies for successful potential revenue streams from a particular track.</p>
<p>The amount of data sourced by user behaviors and features of the songs, all captured by streaming platforms, is very rich. These data make it feasible to predict the volume of streams through algorithms that will help improve engagement, resulting in maximization of consumption and revenue.</p>
<p>In all this context, I will use a dataset available in <a href="https://www.kaggle.com/datasets/nelgiriyewithana/top-spotify-songs-2023">Kaggle (Spotify 2023 data)</a> that contains real data about streaming volumes in Spotify and many features of the songs. I’ll use this dataset to create a model that best predict the number of streams for the songs.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The author describes the dataset as follows:
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>“This dataset contains a comprehensive list of the most famous songs of 2023 as listed on Spotify. The dataset offers a wealth of features beyond what is typically available in similar datasets. It provides insights into each song’s attributes, popularity, and presence on various music platforms. The dataset includes information such as track name, artist(s) name, release date, Spotify playlists and charts, streaming statistics, Apple Music presence, Deezer presence, Shazam charts, and various audio features.”</em></p>
</div>
</div>
</section>
<section id="section-2---exploratory-data-analysis" class="level1">
<h1>Section 2 - Exploratory Data Analysis</h1>
<p>First I’ll load packages and read and create the dataset object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(tidyverse, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(data.table, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(Metrics))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(scales, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(formattable, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(kableExtra, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(ggplot2, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(psych, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(summarytools, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(caret, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(corrplot, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(ggpubr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(tinytex, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(tidymodels, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(glmnet,  <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(randomForest, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(e1071, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressWarnings</span>(<span class="fu">library</span>(ranger, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>conflicted<span class="sc">::</span><span class="fu">conflicts_prefer</span>(yardstick<span class="sc">::</span>accuracy)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>conflicted<span class="sc">::</span><span class="fu">conflicts_prefer</span>(Metrics<span class="sc">::</span>mae)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>tidymodels<span class="sc">::</span> <span class="fu">tidymodels_prefer</span>(<span class="at">quiet =</span> <span class="cn">TRUE</span>) </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading the data.</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>spotify <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"C:/Users/fbeta/OneDrive/Blue Cognition/Blog/R-Blog-BlueCognition/data/spotify-2023.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section-2.1---data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="section-2.1---data-cleaning">Section 2.1 - Data Cleaning</h2>
<p>Let’s see what is in the dataset train file and do some data wrangling as needed and avoiding data leakage.</p>
<p>First, I found that the author of the data describe the deifnition of each feature in the dataset:</p>
<p>track_name: Name of the song artist(s)</p>
<p>name: Name of the artist(s) of the song</p>
<p>artist_count: Number of artists contributing to the song</p>
<p>released_year: Year when the song was released</p>
<p>released_month: Month when the song was released</p>
<p>released_day: Day of the month when the song was released</p>
<p>in_spotify_playlists: Number of Spotify playlists the song is included in</p>
<p>in_spotify_charts: Presence and rank of the song on Spotify charts</p>
<p>streams: Total number of streams on Spotify</p>
<p>in_apple_playlists: Number of Apple Music playlists the song is included</p>
<p>in in_apple_charts: Presence and rank of the song on Apple Music charts</p>
<p>in_deezer_playlists: Number of Deezer playlists the song is included in</p>
<p>in_deezer_charts: Presence and rank of the song on Deezer charts</p>
<p>in_shazam_charts: Presence and rank of the song on Shazam charts</p>
<p>bpm: Beats per minute, a measure of song tempo</p>
<p>key: Key of the song</p>
<p>mode: Mode of the song (major or minor)</p>
<p>danceability_%: Percentage indicating how suitable the song is for dancing</p>
<p>valence_%: Positivity of the song’s musical content</p>
<p>energy_%: Perceived energy level of the song</p>
<p>acousticness_%: Amount of acoustic sound in the song</p>
<p>instrumentalness_%: Amount of instrumental content in the song</p>
<p>liveness_%: Presence of live performance elements</p>
<p>speechiness_%: Amount of spoken words in the song</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Structure and summary of the data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(spotify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   953 obs. of  24 variables:
 $ track_name          : chr  "Seven (feat. Latto) (Explicit Ver.)" "LALA" "vampire" "Cruel Summer" ...
 $ artist.s._name      : chr  "Latto, Jung Kook" "Myke Towers" "Olivia Rodrigo" "Taylor Swift" ...
 $ artist_count        : int  2 1 1 1 1 2 2 1 1 2 ...
 $ released_year       : int  2023 2023 2023 2019 2023 2023 2023 2023 2023 2023 ...
 $ released_month      : int  7 3 6 8 5 6 3 7 5 3 ...
 $ released_day        : int  14 23 30 23 18 1 16 7 15 17 ...
 $ in_spotify_playlists: int  553 1474 1397 7858 3133 2186 3090 714 1096 2953 ...
 $ in_spotify_charts   : int  147 48 113 100 50 91 50 43 83 44 ...
 $ streams             : chr  "141381703" "133716286" "140003974" "800840817" ...
 $ in_apple_playlists  : int  43 48 94 116 84 67 34 25 60 49 ...
 $ in_apple_charts     : int  263 126 207 207 133 213 222 89 210 110 ...
 $ in_deezer_playlists : chr  "45" "58" "91" "125" ...
 $ in_deezer_charts    : int  10 14 14 12 15 17 13 13 11 13 ...
 $ in_shazam_charts    : chr  "826" "382" "949" "548" ...
 $ bpm                 : int  125 92 138 170 144 141 148 100 130 170 ...
 $ key                 : chr  "B" "C#" "F" "A" ...
 $ mode                : chr  "Major" "Major" "Major" "Major" ...
 $ danceability_.      : int  80 71 51 55 65 92 67 67 85 81 ...
 $ valence_.           : int  89 61 32 58 23 66 83 26 22 56 ...
 $ energy_.            : int  83 74 53 72 80 58 76 71 62 48 ...
 $ acousticness_.      : int  31 7 17 11 14 19 48 37 12 21 ...
 $ instrumentalness_.  : int  0 0 0 0 63 0 0 0 0 0 ...
 $ liveness_.          : int  8 10 31 11 11 8 8 11 28 8 ...
 $ speechiness_.       : int  4 4 6 15 6 24 3 4 9 33 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spotify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  track_name        artist.s._name      artist_count   released_year 
 Length:953         Length:953         Min.   :1.000   Min.   :1930  
 Class :character   Class :character   1st Qu.:1.000   1st Qu.:2020  
 Mode  :character   Mode  :character   Median :1.000   Median :2022  
                                       Mean   :1.556   Mean   :2018  
                                       3rd Qu.:2.000   3rd Qu.:2022  
                                       Max.   :8.000   Max.   :2023  
 released_month    released_day   in_spotify_playlists in_spotify_charts
 Min.   : 1.000   Min.   : 1.00   Min.   :   31        Min.   :  0.00   
 1st Qu.: 3.000   1st Qu.: 6.00   1st Qu.:  875        1st Qu.:  0.00   
 Median : 6.000   Median :13.00   Median : 2224        Median :  3.00   
 Mean   : 6.034   Mean   :13.93   Mean   : 5200        Mean   : 12.01   
 3rd Qu.: 9.000   3rd Qu.:22.00   3rd Qu.: 5542        3rd Qu.: 16.00   
 Max.   :12.000   Max.   :31.00   Max.   :52898        Max.   :147.00   
   streams          in_apple_playlists in_apple_charts  in_deezer_playlists
 Length:953         Min.   :  0.00     Min.   :  0.00   Length:953         
 Class :character   1st Qu.: 13.00     1st Qu.:  7.00   Class :character   
 Mode  :character   Median : 34.00     Median : 38.00   Mode  :character   
                    Mean   : 67.81     Mean   : 51.91                      
                    3rd Qu.: 88.00     3rd Qu.: 87.00                      
                    Max.   :672.00     Max.   :275.00                      
 in_deezer_charts in_shazam_charts        bpm            key           
 Min.   : 0.000   Length:953         Min.   : 65.0   Length:953        
 1st Qu.: 0.000   Class :character   1st Qu.:100.0   Class :character  
 Median : 0.000   Mode  :character   Median :121.0   Mode  :character  
 Mean   : 2.666                      Mean   :122.5                     
 3rd Qu.: 2.000                      3rd Qu.:140.0                     
 Max.   :58.000                      Max.   :206.0                     
     mode           danceability_.    valence_.        energy_.    
 Length:953         Min.   :23.00   Min.   : 4.00   Min.   : 9.00  
 Class :character   1st Qu.:57.00   1st Qu.:32.00   1st Qu.:53.00  
 Mode  :character   Median :69.00   Median :51.00   Median :66.00  
                    Mean   :66.97   Mean   :51.43   Mean   :64.28  
                    3rd Qu.:78.00   3rd Qu.:70.00   3rd Qu.:77.00  
                    Max.   :96.00   Max.   :97.00   Max.   :97.00  
 acousticness_.  instrumentalness_.   liveness_.    speechiness_.  
 Min.   : 0.00   Min.   : 0.000     Min.   : 3.00   Min.   : 2.00  
 1st Qu.: 6.00   1st Qu.: 0.000     1st Qu.:10.00   1st Qu.: 4.00  
 Median :18.00   Median : 0.000     Median :12.00   Median : 6.00  
 Mean   :27.06   Mean   : 1.581     Mean   :18.21   Mean   :10.13  
 3rd Qu.:43.00   3rd Qu.: 0.000     3rd Qu.:24.00   3rd Qu.:11.00  
 Max.   :97.00   Max.   :91.000     Max.   :97.00   Max.   :64.00  </code></pre>
</div>
</div>
<p>I will make some obvious adjustments to certain variables, for example the number of “streams” have to be numeric, for some reason it is set as character. Also I’ll fix some features names in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mutating to numeric variables that should be numeric (streams</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>spotify<span class="sc">$</span>streams <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(spotify<span class="sc">$</span>streams)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>spotify<span class="sc">$</span>in_deezer_playlists <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(spotify<span class="sc">$</span>in_deezer_playlists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>spotify<span class="sc">$</span>in_shazam_charts <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(spotify<span class="sc">$</span>in_shazam_charts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll remove special characters from Artist name and track name. </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>spotify <span class="ot">&lt;-</span> spotify <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">artist.s._name =</span> <span class="fu">str_remove_all</span>(artist.s._name, <span class="st">"[^[:alnum:]]"</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>spotify <span class="ot">&lt;-</span> spotify <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">track_name =</span> <span class="fu">str_remove_all</span>(track_name, <span class="st">"[^[:alnum:]]"</span>))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Now I'll create an ID column by merging these 2 columns</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>spotify<span class="sc">$</span>id <span class="ot">&lt;-</span> <span class="fu">paste</span>(spotify<span class="sc">$</span>track_name, spotify<span class="sc">$</span>artist.s._name)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Eliminating spaces</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>spotify <span class="ot">&lt;-</span> spotify <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">id =</span> <span class="fu">str_remove_all</span>(id, <span class="st">"[^[:alnum:]]"</span>))</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming some features names to facilitate the coding later</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>spotify <span class="ot">&lt;-</span> <span class="fu">rename</span>(spotify, <span class="at">artist.name =</span> artist.s._name, <span class="at">number.art.song =</span> artist_count, <span class="at">danceability =</span> danceability_., <span class="at">valence =</span> valence_., <span class="at">energy =</span> energy_., <span class="at">acousticness =</span> acousticness_., <span class="at">instrumentalness =</span> instrumentalness_., <span class="at">liveness =</span> liveness_., <span class="at">speechiness =</span> speechiness_.)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's check how the df looks now</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(spotify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 953  25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(spotify)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  track_name        artist.name        number.art.song released_year 
 Length:953         Length:953         Min.   :1.000   Min.   :1930  
 Class :character   Class :character   1st Qu.:1.000   1st Qu.:2020  
 Mode  :character   Mode  :character   Median :1.000   Median :2022  
                                       Mean   :1.556   Mean   :2018  
                                       3rd Qu.:2.000   3rd Qu.:2022  
                                       Max.   :8.000   Max.   :2023  
                                                                     
 released_month    released_day   in_spotify_playlists in_spotify_charts
 Min.   : 1.000   Min.   : 1.00   Min.   :   31        Min.   :  0.00   
 1st Qu.: 3.000   1st Qu.: 6.00   1st Qu.:  875        1st Qu.:  0.00   
 Median : 6.000   Median :13.00   Median : 2224        Median :  3.00   
 Mean   : 6.034   Mean   :13.93   Mean   : 5200        Mean   : 12.01   
 3rd Qu.: 9.000   3rd Qu.:22.00   3rd Qu.: 5542        3rd Qu.: 16.00   
 Max.   :12.000   Max.   :31.00   Max.   :52898        Max.   :147.00   
                                                                        
    streams          in_apple_playlists in_apple_charts  in_deezer_playlists
 Min.   :2.762e+03   Min.   :  0.00     Min.   :  0.00   Min.   :  0.0      
 1st Qu.:1.416e+08   1st Qu.: 13.00     1st Qu.:  7.00   1st Qu.: 12.0      
 Median :2.905e+08   Median : 34.00     Median : 38.00   Median : 36.5      
 Mean   :5.141e+08   Mean   : 67.81     Mean   : 51.91   Mean   :109.7      
 3rd Qu.:6.739e+08   3rd Qu.: 88.00     3rd Qu.: 87.00   3rd Qu.:110.0      
 Max.   :3.704e+09   Max.   :672.00     Max.   :275.00   Max.   :974.0      
 NA's   :1                                               NA's   :79         
 in_deezer_charts in_shazam_charts      bpm            key           
 Min.   : 0.000   Min.   :  0.00   Min.   : 65.0   Length:953        
 1st Qu.: 0.000   1st Qu.:  0.00   1st Qu.:100.0   Class :character  
 Median : 0.000   Median :  2.00   Median :121.0   Mode  :character  
 Mean   : 2.666   Mean   : 51.18   Mean   :122.5                     
 3rd Qu.: 2.000   3rd Qu.: 36.00   3rd Qu.:140.0                     
 Max.   :58.000   Max.   :953.00   Max.   :206.0                     
                  NA's   :57                                         
     mode            danceability      valence          energy     
 Length:953         Min.   :23.00   Min.   : 4.00   Min.   : 9.00  
 Class :character   1st Qu.:57.00   1st Qu.:32.00   1st Qu.:53.00  
 Mode  :character   Median :69.00   Median :51.00   Median :66.00  
                    Mean   :66.97   Mean   :51.43   Mean   :64.28  
                    3rd Qu.:78.00   3rd Qu.:70.00   3rd Qu.:77.00  
                    Max.   :96.00   Max.   :97.00   Max.   :97.00  
                                                                   
  acousticness   instrumentalness    liveness      speechiness   
 Min.   : 0.00   Min.   : 0.000   Min.   : 3.00   Min.   : 2.00  
 1st Qu.: 6.00   1st Qu.: 0.000   1st Qu.:10.00   1st Qu.: 4.00  
 Median :18.00   Median : 0.000   Median :12.00   Median : 6.00  
 Mean   :27.06   Mean   : 1.581   Mean   :18.21   Mean   :10.13  
 3rd Qu.:43.00   3rd Qu.: 0.000   3rd Qu.:24.00   3rd Qu.:11.00  
 Max.   :97.00   Max.   :91.000   Max.   :97.00   Max.   :64.00  
                                                                 
      id           
 Length:953        
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
</div>
</section>
<section id="section-2.2---numerical-and-visual-summary" class="level2">
<h2 class="anchored" data-anchor-id="section-2.2---numerical-and-visual-summary">Section 2.2 - Numerical and Visual Summary</h2>
<p>Let’s split the dataset, explore more the data to do some wrangling and visualize some key variables in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># splitting dataset to have classifications to test. I will randomly split the dataset into 80% for training and 20% for testing</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">197</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>ran <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(spotify), <span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(spotify)) </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the data into training and testing sets</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> spotify[ran,]</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> spotify[<span class="sc">-</span>ran,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking the dimensions of the new datasets</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 762  25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 191  25</code></pre>
</div>
</div>
<p>Training set has 762 rows/observations and 38 features or variables, while the test set contain 191 observations and the same 38 variables.</p>
<p>I’ll do some data wrangling for the train set</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's review the character variables and create dummies that can be use later when building the models</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(train<span class="sc">$</span>key)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "F#" "G"  "D"  "G#" "A#" "E"  "C#" ""   "A"  "D#" "F"  "B" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(train<span class="sc">$</span>mode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Minor" "Major"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploring the frequency of the values in the key</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>key.table<span class="ot">&lt;-</span><span class="fu">table</span>(train<span class="sc">$</span>key)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>key.table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    A A#  B C#  D D#  E  F F#  G G# 
74 61 43 65 94 62 28 51 69 64 82 69 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#replacing blank cells with NA</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>train<span class="sc">$</span>key <span class="ot">&lt;-</span> <span class="fu">na_if</span>(train<span class="sc">$</span>key, <span class="st">''</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#replacing NA with the most frequent value in the feature, in this case C#</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(key), <span class="st">"C#"</span>, key))</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll create dummy for key and mode </span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mode.n =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        mode <span class="sc">==</span> <span class="st">"Major"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>        mode <span class="sc">==</span> <span class="st">"Minor"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        ))<span class="sc">%&gt;%</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.A =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"A"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.B =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"B"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.D =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"D"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.E =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"E"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.F =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"F"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.G =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"G"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.CS =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"C#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-38"><a href="#cb27-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.FS =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-39"><a href="#cb27-39" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"F#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-40"><a href="#cb27-40" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-41"><a href="#cb27-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.GS =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-42"><a href="#cb27-42" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"G#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-43"><a href="#cb27-43" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-44"><a href="#cb27-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.AS =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-45"><a href="#cb27-45" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"A#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-46"><a href="#cb27-46" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb27-47"><a href="#cb27-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.DS =</span> <span class="fu">case_when</span>(</span>
<span id="cb27-48"><a href="#cb27-48" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"D#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb27-49"><a href="#cb27-49" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb27-50"><a href="#cb27-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-51"><a href="#cb27-51" aria-hidden="true" tabindex="-1"></a><span class="co">#Lastly I'll replace the some NAs using median. For in_deezer_playlists, in_shazam_charts and stream</span></span>
<span id="cb27-52"><a href="#cb27-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-53"><a href="#cb27-53" aria-hidden="true" tabindex="-1"></a>median.stream.t <span class="ot">&lt;-</span> <span class="fu">median</span>(train<span class="sc">$</span>streams, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-54"><a href="#cb27-54" aria-hidden="true" tabindex="-1"></a>median.deezer.playlist.t <span class="ot">&lt;-</span> <span class="fu">median</span>(train<span class="sc">$</span>in_deezer_playlists, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-55"><a href="#cb27-55" aria-hidden="true" tabindex="-1"></a>median.shazam.chart.t <span class="ot">&lt;-</span> <span class="fu">median</span>(train<span class="sc">$</span>in_shazam_charts, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-56"><a href="#cb27-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-57"><a href="#cb27-57" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">streams =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(streams), median.stream.t, streams)) <span class="sc">%&gt;%</span></span>
<span id="cb27-58"><a href="#cb27-58" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">mutate</span>(<span class="at">in_deezer_playlists =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(in_deezer_playlists), median.deezer.playlist.t, in_deezer_playlists)) <span class="sc">%&gt;%</span></span>
<span id="cb27-59"><a href="#cb27-59" aria-hidden="true" tabindex="-1"></a>                   <span class="fu">mutate</span>(<span class="at">in_shazam_charts =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(in_shazam_charts), median.shazam.chart.t, in_shazam_charts))</span>
<span id="cb27-60"><a href="#cb27-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-61"><a href="#cb27-61" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  track_name        artist.name        number.art.song released_year 
 Length:762         Length:762         Min.   :1.000   Min.   :1930  
 Class :character   Class :character   1st Qu.:1.000   1st Qu.:2020  
 Mode  :character   Mode  :character   Median :1.000   Median :2022  
                                       Mean   :1.539   Mean   :2018  
                                       3rd Qu.:2.000   3rd Qu.:2022  
                                       Max.   :8.000   Max.   :2023  
 released_month    released_day   in_spotify_playlists in_spotify_charts
 Min.   : 1.000   Min.   : 1.00   Min.   :   31.0      Min.   :  0.00   
 1st Qu.: 3.000   1st Qu.: 6.00   1st Qu.:  853.8      1st Qu.:  0.00   
 Median : 5.000   Median :13.00   Median : 2167.0      Median :  3.00   
 Mean   : 6.004   Mean   :13.86   Mean   : 5188.8      Mean   : 11.86   
 3rd Qu.: 9.000   3rd Qu.:22.00   3rd Qu.: 5412.0      3rd Qu.: 15.75   
 Max.   :12.000   Max.   :31.00   Max.   :52898.0      Max.   :147.00   
    streams          in_apple_playlists in_apple_charts  in_deezer_playlists
 Min.   :2.762e+03   Min.   :  0.00     Min.   :  0.00   Min.   :  0.00     
 1st Qu.:1.397e+08   1st Qu.: 13.00     1st Qu.:  7.00   1st Qu.: 13.00     
 Median :2.867e+08   Median : 34.50     Median : 38.00   Median : 35.00     
 Mean   :5.051e+08   Mean   : 66.10     Mean   : 52.61   Mean   : 97.88     
 3rd Qu.:6.573e+08   3rd Qu.: 83.75     3rd Qu.: 87.00   3rd Qu.: 93.00     
 Max.   :3.563e+09   Max.   :537.00     Max.   :275.00   Max.   :974.00     
 in_deezer_charts in_shazam_charts      bpm             key           
 Min.   : 0.000   Min.   :  0.0    Min.   : 65.00   Length:762        
 1st Qu.: 0.000   1st Qu.:  0.0    1st Qu.: 98.25   Class :character  
 Median : 0.000   Median :  2.0    Median :121.00   Mode  :character  
 Mean   : 2.554   Mean   : 50.1    Mean   :122.36                     
 3rd Qu.: 2.000   3rd Qu.: 31.0    3rd Qu.:140.00                     
 Max.   :58.000   Max.   :953.0    Max.   :206.00                     
     mode            danceability      valence          energy     
 Length:762         Min.   :23.00   Min.   : 4.00   Min.   : 9.00  
 Class :character   1st Qu.:57.00   1st Qu.:32.00   1st Qu.:54.00  
 Mode  :character   Median :69.00   Median :51.00   Median :66.00  
                    Mean   :66.69   Mean   :51.50   Mean   :64.22  
                    3rd Qu.:78.00   3rd Qu.:70.75   3rd Qu.:77.00  
                    Max.   :95.00   Max.   :97.00   Max.   :97.00  
  acousticness   instrumentalness    liveness      speechiness   
 Min.   : 0.00   Min.   : 0.000   Min.   : 3.00   Min.   : 2.00  
 1st Qu.: 6.00   1st Qu.: 0.000   1st Qu.:10.00   1st Qu.: 4.00  
 Median :17.00   Median : 0.000   Median :12.00   Median : 6.00  
 Mean   :27.42   Mean   : 1.682   Mean   :18.12   Mean   :10.12  
 3rd Qu.:44.00   3rd Qu.: 0.000   3rd Qu.:23.00   3rd Qu.:11.00  
 Max.   :97.00   Max.   :91.000   Max.   :91.00   Max.   :64.00  
      id                mode.n          key.A             key.B       
 Length:762         Min.   :0.000   Min.   :0.00000   Min.   :0.0000  
 Class :character   1st Qu.:0.000   1st Qu.:0.00000   1st Qu.:0.0000  
 Mode  :character   Median :1.000   Median :0.00000   Median :0.0000  
                    Mean   :0.584   Mean   :0.08005   Mean   :0.0853  
                    3rd Qu.:1.000   3rd Qu.:0.00000   3rd Qu.:0.0000  
                    Max.   :1.000   Max.   :1.00000   Max.   :1.0000  
     key.D             key.E             key.F             key.G       
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.0000  
 Median :0.00000   Median :0.00000   Median :0.00000   Median :0.0000  
 Mean   :0.08136   Mean   :0.06693   Mean   :0.09055   Mean   :0.1076  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.0000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000   Max.   :1.0000  
     key.CS           key.FS            key.GS            key.AS       
 Min.   :0.0000   Min.   :0.00000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000  
 Median :0.0000   Median :0.00000   Median :0.00000   Median :0.00000  
 Mean   :0.2205   Mean   :0.08399   Mean   :0.09055   Mean   :0.05643  
 3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :1.0000   Max.   :1.00000   Max.   :1.00000   Max.   :1.00000  
     key.DS       
 Min.   :0.00000  
 1st Qu.:0.00000  
 Median :0.00000  
 Mean   :0.03675  
 3rd Qu.:0.00000  
 Max.   :1.00000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 762  37</code></pre>
</div>
</div>
<p>Now let’s explore the training dataset with focus on Streams which is the target variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's see a summary of the target variable (number of streams)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>summary.stream <span class="ot">&lt;-</span> <span class="fu">descr</span>(train<span class="sc">$</span>streams)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary.stream)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Descriptive Statistics  
train$streams  
N: 762  

                          streams
----------------- ---------------
             Mean    505056426.77
          Std.Dev    555606450.79
              Min         2762.00
               Q1    139681964.00
           Median    286739476.00
               Q3    657723613.00
              Max   3562543890.00
              MAD    275729763.36
              IQR    517575700.75
               CV            1.10
         Skewness            1.98
      SE.Skewness            0.09
         Kurtosis            4.12
          N.Valid          762.00
        Pct.Valid          100.00</code></pre>
</div>
</div>
<p>Given the difference between Mean and Median (~2x) and curtosis value (&gt;0 - 4.12), it sounds like a distribution far to a normal distribution with high probability of extreme values.</p>
<p>Let’s visualize the distribution. I’ll use a density plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Density estimation</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>density_streams <span class="ot">&lt;-</span> <span class="fu">density</span>(train<span class="sc">$</span>streams)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>density_spot_play <span class="ot">&lt;-</span> <span class="fu">density</span>(train<span class="sc">$</span>in_spotify_playlists)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>density_app_play <span class="ot">&lt;-</span> <span class="fu">density</span>(train<span class="sc">$</span>in_apple_playlists)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>density_dee_play <span class="ot">&lt;-</span> <span class="fu">density</span>(train<span class="sc">$</span>in_deezer_playlists)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>density_acc <span class="ot">&lt;-</span> <span class="fu">density</span>(train<span class="sc">$</span>acousticness)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the density curve</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(density_streams, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">main =</span> <span class="st">"Density Plot for Streams"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(density_spot_play, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">main =</span> <span class="st">"Density Plot for In Spotify Playlist"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(density_app_play, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">main =</span> <span class="st">"Density Plot for In Apple Playlist"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(density_dee_play, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">main =</span> <span class="st">"Density Plot for In Deezer Playlist"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(density_acc, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">main =</span> <span class="st">"Density Plot for Acousticness"</span>, <span class="at">xlab =</span> <span class="st">"Values"</span>, <span class="at">ylab =</span> <span class="st">"Density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Certainly the distribution seems with a very heavy tail towards the higher values. Also looking at some key variables</p>
<p>It seems that just a few artist has a very high volume of streams represented by extreme values.</p>
<p>Just curious about the streams by artist:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's create a table summarizing streams by artist</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>dt.train <span class="ot">&lt;-</span> <span class="fu">data.table</span>(train)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>dt.train2 <span class="ot">&lt;-</span> dt.train[,<span class="fu">list</span>(<span class="at">Total.streams =</span> <span class="fu">sum</span>(streams, <span class="at">na.rm=</span>T), <span class="at">freq =</span> .N), by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"artist.name"</span>)]</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>Stream_table <span class="ot">&lt;-</span> dt.train2 <span class="sc">%&gt;%</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(artist.name) <span class="sc">%&gt;%</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Total.streams =</span> <span class="fu">sum</span>(Total.streams, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">Streams.Median =</span> <span class="fu">median</span>(Total.streams, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>Stream_table <span class="ot">&lt;-</span> Stream_table <span class="sc">%&gt;%</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Total.Streams.Percent =</span> Total.streams<span class="sc">/</span>(<span class="fu">sum</span>(Total.streams))<span class="sc">*</span><span class="fl">100.2</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>Stream_table <span class="ot">&lt;-</span> Stream_table[<span class="fu">with</span> (Stream_table, <span class="fu">order</span>(<span class="sc">-</span>Total.Streams.Percent)),]</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>Stream_table <span class="ot">&lt;-</span> Stream_table<span class="sc">%&gt;%</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Cum_Percent =</span> <span class="fu">cumsum</span>(Total.Streams.Percent))</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>data_subset <span class="ot">&lt;-</span> <span class="fu">slice</span>(Stream_table, <span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the subset of the data as a nice table using kable</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(data_subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">artist.name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total.streams</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Streams.Median</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total.Streams.Percent</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Cum_Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EdSheeran</td>
<td style="text-align: right;">12411186494</td>
<td style="text-align: right;">12411186494</td>
<td style="text-align: right;">3.2313660</td>
<td style="text-align: right;">3.231366</td>
</tr>
<tr class="even">
<td style="text-align: left;">TaylorSwift</td>
<td style="text-align: right;">10812098960</td>
<td style="text-align: right;">10812098960</td>
<td style="text-align: right;">2.8150289</td>
<td style="text-align: right;">6.046395</td>
</tr>
<tr class="odd">
<td style="text-align: left;">HarryStyles</td>
<td style="text-align: right;">9098362425</td>
<td style="text-align: right;">9098362425</td>
<td style="text-align: right;">2.3688419</td>
<td style="text-align: right;">8.415237</td>
</tr>
<tr class="even">
<td style="text-align: left;">TheWeeknd</td>
<td style="text-align: right;">8957974292</td>
<td style="text-align: right;">8957974292</td>
<td style="text-align: right;">2.3322906</td>
<td style="text-align: right;">10.747527</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BadBunny</td>
<td style="text-align: right;">5925299832</td>
<td style="text-align: right;">5925299832</td>
<td style="text-align: right;">1.5427060</td>
<td style="text-align: right;">12.290233</td>
</tr>
<tr class="even">
<td style="text-align: left;">OliviaRodrigo</td>
<td style="text-align: right;">4889343765</td>
<td style="text-align: right;">4889343765</td>
<td style="text-align: right;">1.2729854</td>
<td style="text-align: right;">13.563219</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ImagineDragons</td>
<td style="text-align: right;">4434404750</td>
<td style="text-align: right;">4434404750</td>
<td style="text-align: right;">1.1545379</td>
<td style="text-align: right;">14.717757</td>
</tr>
<tr class="even">
<td style="text-align: left;">BrunoMars</td>
<td style="text-align: right;">4185733280</td>
<td style="text-align: right;">4185733280</td>
<td style="text-align: right;">1.0897940</td>
<td style="text-align: right;">15.807551</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TheNeighbourhood</td>
<td style="text-align: right;">4010009939</td>
<td style="text-align: right;">4010009939</td>
<td style="text-align: right;">1.0440428</td>
<td style="text-align: right;">16.851593</td>
</tr>
<tr class="even">
<td style="text-align: left;">ArcticMonkeys</td>
<td style="text-align: right;">3781480286</td>
<td style="text-align: right;">3781480286</td>
<td style="text-align: right;">0.9845430</td>
<td style="text-align: right;">17.836136</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DojaCat</td>
<td style="text-align: right;">3659726247</td>
<td style="text-align: right;">3659726247</td>
<td style="text-align: right;">0.9528432</td>
<td style="text-align: right;">18.788980</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eminem</td>
<td style="text-align: right;">3254582526</td>
<td style="text-align: right;">3254582526</td>
<td style="text-align: right;">0.8473603</td>
<td style="text-align: right;">19.636340</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DuaLipa</td>
<td style="text-align: right;">3227639000</td>
<td style="text-align: right;">3227639000</td>
<td style="text-align: right;">0.8403454</td>
<td style="text-align: right;">20.476685</td>
</tr>
<tr class="even">
<td style="text-align: left;">LewisCapaldi</td>
<td style="text-align: right;">3126653123</td>
<td style="text-align: right;">3126653123</td>
<td style="text-align: right;">0.8140528</td>
<td style="text-align: right;">21.290738</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OneRepublic</td>
<td style="text-align: right;">3097149603</td>
<td style="text-align: right;">3097149603</td>
<td style="text-align: right;">0.8063712</td>
<td style="text-align: right;">22.097109</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adele</td>
<td style="text-align: right;">3035946717</td>
<td style="text-align: right;">3035946717</td>
<td style="text-align: right;">0.7904365</td>
<td style="text-align: right;">22.887546</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LinkinPark</td>
<td style="text-align: right;">2985590613</td>
<td style="text-align: right;">2985590613</td>
<td style="text-align: right;">0.7773258</td>
<td style="text-align: right;">23.664872</td>
</tr>
<tr class="even">
<td style="text-align: left;">BTS</td>
<td style="text-align: right;">2944237123</td>
<td style="text-align: right;">2944237123</td>
<td style="text-align: right;">0.7665591</td>
<td style="text-align: right;">24.431431</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TonesandI</td>
<td style="text-align: right;">2864791672</td>
<td style="text-align: right;">2864791672</td>
<td style="text-align: right;">0.7458747</td>
<td style="text-align: right;">25.177306</td>
</tr>
<tr class="even">
<td style="text-align: left;">SZA</td>
<td style="text-align: right;">2843515815</td>
<td style="text-align: right;">2843515815</td>
<td style="text-align: right;">0.7403354</td>
<td style="text-align: right;">25.917641</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PostMaloneSwaeLee</td>
<td style="text-align: right;">2808096550</td>
<td style="text-align: right;">2808096550</td>
<td style="text-align: right;">0.7311136</td>
<td style="text-align: right;">26.648755</td>
</tr>
<tr class="even">
<td style="text-align: left;">JustinBieber</td>
<td style="text-align: right;">2752482785</td>
<td style="text-align: right;">2752482785</td>
<td style="text-align: right;">0.7166341</td>
<td style="text-align: right;">27.365389</td>
</tr>
<tr class="odd">
<td style="text-align: left;">KendrickLamar</td>
<td style="text-align: right;">2689179073</td>
<td style="text-align: right;">2689179073</td>
<td style="text-align: right;">0.7001524</td>
<td style="text-align: right;">28.065541</td>
</tr>
<tr class="even">
<td style="text-align: left;">JamesArthur</td>
<td style="text-align: right;">2686344050</td>
<td style="text-align: right;">2686344050</td>
<td style="text-align: right;">0.6994143</td>
<td style="text-align: right;">28.764955</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TheChainsmokersHalsey</td>
<td style="text-align: right;">2591224264</td>
<td style="text-align: right;">2591224264</td>
<td style="text-align: right;">0.6746490</td>
<td style="text-align: right;">29.439604</td>
</tr>
<tr class="even">
<td style="text-align: left;">TheWeekndDaftPunk</td>
<td style="text-align: right;">2565529693</td>
<td style="text-align: right;">2565529693</td>
<td style="text-align: right;">0.6679591</td>
<td style="text-align: right;">30.107563</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GlassAnimals</td>
<td style="text-align: right;">2557975762</td>
<td style="text-align: right;">2557975762</td>
<td style="text-align: right;">0.6659924</td>
<td style="text-align: right;">30.773556</td>
</tr>
<tr class="even">
<td style="text-align: left;">ShawnMendesCamilaCabello</td>
<td style="text-align: right;">2484812918</td>
<td style="text-align: right;">2484812918</td>
<td style="text-align: right;">0.6469438</td>
<td style="text-align: right;">31.420500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mne</td>
<td style="text-align: right;">2450538862</td>
<td style="text-align: right;">2450538862</td>
<td style="text-align: right;">0.6380202</td>
<td style="text-align: right;">32.058520</td>
</tr>
<tr class="even">
<td style="text-align: left;">Joji</td>
<td style="text-align: right;">2357270185</td>
<td style="text-align: right;">2357270185</td>
<td style="text-align: right;">0.6137369</td>
<td style="text-align: right;">32.672257</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>It is interesting to see that almost 10% of total streams are concentrated in 4 artist: Ed Sheeran, Tylor Swift, Harry Styles and The Weeknd. And 30% of all streams comes from 26 artists.</p>
<p>It is important to mention that here “artist” means unique artist or combination of artists per song, for example, if Taylor Swift has a song along with Ed Sheeran, then it will be considered a unique artist in the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#how many unique artist are here</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(train<span class="sc">$</span>artist.name)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 536</code></pre>
</div>
</div>
<p>We have 536 “unique” artist, so following previous observation we can say that 5% of the artist (26 artists) concentrate 30% of all streams.</p>
<p>Something that I think would be interesting is segmenting the data set in Deciles to create categories of artist from the highest to lowest streamer.</p>
<p>Then we can use those categories as a classification target.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's create the Decile variable based on the streams to use it later in classification method</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">class.decile =</span> <span class="fu">ntile</span>(streams, <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s explore a few other features vs streams</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Box plot for Strems and Mode, Key and Number of Artists in the song</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>box1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x =</span>mode, <span class="at">y =</span> streams))<span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>number.art.song, <span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span>  <span class="fu">c</span>(<span class="fl">1e+7</span>, <span class="fl">1e+9</span>))<span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Streams vs Mode"</span>,</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Grouped by Number of Artist in the Song"</span>,</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Mode"</span>, <span class="at">y =</span> <span class="st">"Streams"</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>box1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="1440"></p>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>box2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train, <span class="fu">aes</span>(<span class="at">x =</span>key, <span class="at">y =</span> streams))<span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha=</span><span class="fl">0.7</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>)<span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(.<span class="sc">~</span>number.art.song, <span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))<span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span>  <span class="fu">c</span>(<span class="fl">1e+7</span>, <span class="fl">1.5e+9</span>))<span class="sc">+</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Streams vs Key"</span>,</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Grouped by Number of Artist in the Song"</span>,</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"Key"</span>, <span class="at">y =</span> <span class="st">"Streams"</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>box2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="1440"></p>
</div>
</div>
<p>It is interesting to see that there is not too much variability when comparing streams by Mode and Number of Artist in the song, but when comparing among Keys seems that the variability increases when the song has 2 or 3 artists involved.</p>
<p>Let’s now look at numerical variables using correlation matrix and scatter plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll create a dataset with only numeric variables, also I will exclude from here class.decile because is redundnat with streams</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>train.n <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>track_name, <span class="sc">-</span>artist.name, <span class="sc">-</span>key, <span class="sc">-</span>mode, <span class="sc">-</span>id, <span class="sc">-</span>class.decile)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cor Matrix</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>cor_matrix1 <span class="ot">&lt;-</span> <span class="fu">cor</span>(train.n)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>cor_matrix1 <span class="ot">&lt;-</span> <span class="fu">round</span>(cor_matrix1, <span class="dv">2</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's see a color matrix to simplify visualization</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix1, <span class="at">method =</span> <span class="st">"circle"</span>, <span class="at">tl.cex =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I can see that there is correlation among presence in charts and playlists among the different platforms, in particular seems there is a strong correlation between Spotify and Apple Music playlists and among the charts in all platforms. Here could be some milticolinearity that I may need to pay attention.</p>
<p>On the other hand there seems also some multicolinearity among song characteristics (danceability, energy, valence, acousticness, instrumentalness, liveness, speachness), but none of them seems highly correlated to streams. Also noted strong inverse correlation between acousticness and energy).</p>
<p>Lastly, seems that number of streams is highly and positive correlated to the number of playlists the song is included in any of the platforms (spotify, apple and deezer).</p>
<p>Let’s visualize Streams and playlists in scatter plots</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>scatter1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train, <span class="fu">aes</span>(in_deezer_playlists,streams))<span class="sc">+</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="fl">1e+8</span>,<span class="fl">1.5e+9</span>))<span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Streams vs Deezer playlist precense"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"In Deezer Playlist"</span>, <span class="at">y =</span> <span class="st">"Streams"</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>scatter1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 175 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>scatter2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train, <span class="fu">aes</span>(in_apple_playlists,streams))<span class="sc">+</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="fl">1e+8</span>,<span class="fl">1.5e+9</span>))<span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Streams vs Apple playlist precense"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"In Apple Music Playlist"</span>, <span class="at">y =</span> <span class="st">"Streams"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>scatter2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 175 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>scatter3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(train, <span class="fu">aes</span>(in_spotify_playlists,streams))<span class="sc">+</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits=</span><span class="fu">c</span>(<span class="fl">1e+8</span>,<span class="fl">1.5e+9</span>))<span class="sc">+</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatter Plot - Streams vs Spotify playlist precense"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">x =</span><span class="st">"In Spotify Playlist"</span>, <span class="at">y =</span> <span class="st">"Streams"</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>scatter3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 175 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="section-3---evaluation-metric" class="level1">
<h1>Section 3 - Evaluation Metric</h1>
<p>I’ll focus on Regression method for modeling. I have 32 features in my training set including the numerical variables only, and since it can’t be considered a large number of features so I’ll pass on any shrinking method this time (like PCA).</p>
<p>Given the distribution of the target variable (streams) is very skewed and I won’t transform the variable (i.e log), I rather use a metric less sensitive to outliners. So I’ll use <strong>Median Absolute Error</strong> (mdae in R).</p>
</section>
<section id="section-4---fit-models" class="level1">
<h1>Section 4 - Fit models</h1>
<p>I’ll use linear regression, lasso regression and random forest</p>
<section id="section-4.1---data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="section-4.1---data-preprocessing">Section 4.1 - Data preprocessing</h2>
<section id="method-1---linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="method-1---linear-regression">Method 1 - Linear Regression</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Linear regression with all features</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(streams <span class="sc">~</span> ., <span class="at">data =</span> train.n)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = streams ~ ., data = train.n)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.467e+09 -1.336e+08 -3.137e+07  9.722e+07  2.190e+09 

Coefficients: (1 not defined because of singularities)
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          -8.558e+09  2.096e+09  -4.083 4.94e-05 ***
number.art.song      -3.182e+07  1.279e+07  -2.487  0.01311 *  
released_year         4.334e+06  1.039e+06   4.170 3.42e-05 ***
released_month        2.940e+06  3.022e+06   0.973  0.33095    
released_day          3.147e+06  1.153e+06   2.730  0.00648 ** 
in_spotify_playlists  3.793e+04  2.047e+03  18.530  &lt; 2e-16 ***
in_spotify_charts     4.781e+06  7.712e+05   6.200 9.45e-10 ***
in_apple_playlists    2.384e+06  2.048e+05  11.640  &lt; 2e-16 ***
in_apple_charts      -2.736e+05  2.625e+05  -1.042  0.29755    
in_deezer_playlists   4.687e+05  7.101e+04   6.600 7.88e-11 ***
in_deezer_charts     -8.956e+06  2.387e+06  -3.752  0.00019 ***
in_shazam_charts     -4.752e+05  9.508e+04  -4.998 7.25e-07 ***
bpm                   1.812e+04  3.808e+05   0.048  0.96206    
danceability          3.906e+05  8.622e+05   0.453  0.65064    
valence              -6.102e+05  5.438e+05  -1.122  0.26225    
energy               -7.588e+05  8.644e+05  -0.878  0.38032    
acousticness          9.046e+05  5.141e+05   1.760  0.07890 .  
instrumentalness     -1.709e+06  1.188e+06  -1.438  0.15076    
liveness             -1.696e+05  7.826e+05  -0.217  0.82847    
speechiness          -1.247e+06  1.086e+06  -1.149  0.25107    
mode.n                4.972e+06  2.275e+07   0.219  0.82710    
key.A                 1.095e+07  6.603e+07   0.166  0.86837    
key.B                -6.133e+07  6.561e+07  -0.935  0.35027    
key.D                -7.028e+07  6.661e+07  -1.055  0.29171    
key.E                -5.650e+06  6.776e+07  -0.083  0.93357    
key.F                -4.791e+07  6.494e+07  -0.738  0.46090    
key.G                -8.322e+07  6.341e+07  -1.312  0.18977    
key.CS               -7.180e+07  5.961e+07  -1.204  0.22881    
key.FS               -9.925e+07  6.553e+07  -1.515  0.13031    
key.GS               -3.300e+07  6.500e+07  -0.508  0.61177    
key.AS                3.077e+07  7.020e+07   0.438  0.66133    
key.DS                       NA         NA      NA       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 284800000 on 731 degrees of freedom
Multiple R-squared:  0.7477,    Adjusted R-squared:  0.7373 
F-statistic: 72.21 on 30 and 731 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Out of the 31 features only 10 show a significant relationship with the number of streams, most of them around presence in playlists or charts in the different platforms, only one is related to the music compositions (acousticness).</p>
<p>I’ll try other liner models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll log the target to see if the prediction improves</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(streams) <span class="sc">~</span> number.art.song <span class="sc">+</span> released_year <span class="sc">+</span> released_day <span class="sc">+</span> in_spotify_playlists <span class="sc">+</span> in_spotify_charts <span class="sc">+</span> in_apple_playlists <span class="sc">+</span> in_deezer_playlists <span class="sc">+</span> in_deezer_charts <span class="sc">+</span> in_shazam_charts <span class="sc">+</span> acousticness, <span class="at">data =</span> train.n)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(streams) ~ number.art.song + released_year + 
    released_day + in_spotify_playlists + in_spotify_charts + 
    in_apple_playlists + in_deezer_playlists + in_deezer_charts + 
    in_shazam_charts + acousticness, data = train.n)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.9204  -0.4216   0.0697   0.5158   2.0350 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           1.820e+01  5.802e+00   3.138  0.00177 ** 
number.art.song      -8.926e-02  3.492e-02  -2.556  0.01078 *  
released_year         3.179e-04  2.872e-03   0.111  0.91191    
released_day          8.862e-03  3.253e-03   2.724  0.00660 ** 
in_spotify_playlists  5.709e-05  5.663e-06  10.081  &lt; 2e-16 ***
in_spotify_charts     2.409e-03  1.998e-03   1.205  0.22841    
in_apple_playlists    3.415e-03  5.457e-04   6.259 6.51e-10 ***
in_deezer_playlists   1.585e-03  2.002e-04   7.918 8.66e-15 ***
in_deezer_charts     -9.397e-03  6.756e-03  -1.391  0.16467    
in_shazam_charts     -4.756e-04  2.626e-04  -1.811  0.07052 .  
acousticness          1.387e-04  1.142e-03   0.121  0.90340    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8143 on 751 degrees of freedom
Multiple R-squared:  0.5021,    Adjusted R-squared:  0.4955 
F-statistic: 75.75 on 10 and 751 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Actually the model deteriorates significantly when logging streams variable (Adjusted R2=.5 vs .73 with model 1).</p>
<p>A third model keeping only significant features founded in model 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's keep only the significant features</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(streams <span class="sc">~</span> number.art.song <span class="sc">+</span> released_year <span class="sc">+</span> released_day <span class="sc">+</span> in_spotify_playlists <span class="sc">+</span> in_spotify_charts <span class="sc">+</span> in_apple_playlists <span class="sc">+</span> in_deezer_playlists <span class="sc">+</span> in_deezer_charts <span class="sc">+</span> in_shazam_charts <span class="sc">+</span> acousticness, <span class="at">data =</span> train.n)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = streams ~ number.art.song + released_year + released_day + 
    in_spotify_playlists + in_spotify_charts + in_apple_playlists + 
    in_deezer_playlists + in_deezer_charts + in_shazam_charts + 
    acousticness, data = train.n)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.520e+09 -1.330e+08 -3.618e+07  9.146e+07  2.143e+09 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          -9.335e+09  2.032e+09  -4.595 5.08e-06 ***
number.art.song      -3.621e+07  1.223e+07  -2.961 0.003159 ** 
released_year         4.670e+06  1.006e+06   4.643 4.06e-06 ***
released_day          2.793e+06  1.139e+06   2.452 0.014437 *  
in_spotify_playlists  3.770e+04  1.983e+03  19.011  &lt; 2e-16 ***
in_spotify_charts     4.274e+06  6.997e+05   6.108 1.61e-09 ***
in_apple_playlists    2.357e+06  1.911e+05  12.334  &lt; 2e-16 ***
in_deezer_playlists   4.690e+05  7.009e+04   6.691 4.33e-11 ***
in_deezer_charts     -9.241e+06  2.366e+06  -3.906 0.000102 ***
in_shazam_charts     -4.775e+05  9.195e+04  -5.193 2.67e-07 ***
acousticness          1.199e+06  4.000e+05   2.996 0.002823 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 285100000 on 751 degrees of freedom
Multiple R-squared:  0.7401,    Adjusted R-squared:  0.7366 
F-statistic: 213.8 on 10 and 751 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The power of explanation when pulling out non-relevant features (based on the statistical significance) practically does not change.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions for new data</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>predicted_1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, train.n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(model1, train.n): prediction from rank-deficient fit;
attr(*, "non-estim") has doubtful cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>predicted_2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model2, train.n)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>predicted_3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, train.n)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co">#MdAE      </span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>mdae_lm1 <span class="ot">&lt;-</span> <span class="fu">mdae</span>(train.n<span class="sc">$</span>streams, predicted_1)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>mdae_lm2 <span class="ot">&lt;-</span> <span class="fu">mdae</span>(train.n<span class="sc">$</span>streams, predicted_2)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>mdae_lm3 <span class="ot">&lt;-</span> <span class="fu">mdae</span>(train.n<span class="sc">$</span>streams, predicted_3)</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119534826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 286739457</code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 116079107</code></pre>
</div>
</div>
<p>Seems that model 3 is the best option based on the Median Absolute Error value (lowest error). Logging streams makes the model worst, and interesting to see that model 1 which includes all variables and has the highest R2 has a higher error than model 3 which includes only the most relevant features based on the p value significance.</p>
</section>
<section id="method-2---lasso-regression" class="level3">
<h3 class="anchored" data-anchor-id="method-2---lasso-regression">Method 2 - Lasso Regression</h3>
<p>Lasso is particularly useful in situations where feature selection is desired or when the dataset contains many irrelevant or redundant predictors, which seems this case. Also select the most relevant features and reduce coefficient of irrelevant features, which at the same time allows to handle multicollinearity among predictor variables which also seems appropriate given the strong correlation among playlist and chart variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(train.n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> number.art.song released_year  released_month    released_day  
 Min.   :1.000   Min.   :1930   Min.   : 1.000   Min.   : 1.00  
 1st Qu.:1.000   1st Qu.:2020   1st Qu.: 3.000   1st Qu.: 6.00  
 Median :1.000   Median :2022   Median : 5.000   Median :13.00  
 Mean   :1.539   Mean   :2018   Mean   : 6.004   Mean   :13.86  
 3rd Qu.:2.000   3rd Qu.:2022   3rd Qu.: 9.000   3rd Qu.:22.00  
 Max.   :8.000   Max.   :2023   Max.   :12.000   Max.   :31.00  
 in_spotify_playlists in_spotify_charts    streams          in_apple_playlists
 Min.   :   31.0      Min.   :  0.00    Min.   :2.762e+03   Min.   :  0.00    
 1st Qu.:  853.8      1st Qu.:  0.00    1st Qu.:1.397e+08   1st Qu.: 13.00    
 Median : 2167.0      Median :  3.00    Median :2.867e+08   Median : 34.50    
 Mean   : 5188.8      Mean   : 11.86    Mean   :5.051e+08   Mean   : 66.10    
 3rd Qu.: 5412.0      3rd Qu.: 15.75    3rd Qu.:6.573e+08   3rd Qu.: 83.75    
 Max.   :52898.0      Max.   :147.00    Max.   :3.563e+09   Max.   :537.00    
 in_apple_charts  in_deezer_playlists in_deezer_charts in_shazam_charts
 Min.   :  0.00   Min.   :  0.00      Min.   : 0.000   Min.   :  0.0   
 1st Qu.:  7.00   1st Qu.: 13.00      1st Qu.: 0.000   1st Qu.:  0.0   
 Median : 38.00   Median : 35.00      Median : 0.000   Median :  2.0   
 Mean   : 52.61   Mean   : 97.88      Mean   : 2.554   Mean   : 50.1   
 3rd Qu.: 87.00   3rd Qu.: 93.00      3rd Qu.: 2.000   3rd Qu.: 31.0   
 Max.   :275.00   Max.   :974.00      Max.   :58.000   Max.   :953.0   
      bpm          danceability      valence          energy     
 Min.   : 65.00   Min.   :23.00   Min.   : 4.00   Min.   : 9.00  
 1st Qu.: 98.25   1st Qu.:57.00   1st Qu.:32.00   1st Qu.:54.00  
 Median :121.00   Median :69.00   Median :51.00   Median :66.00  
 Mean   :122.36   Mean   :66.69   Mean   :51.50   Mean   :64.22  
 3rd Qu.:140.00   3rd Qu.:78.00   3rd Qu.:70.75   3rd Qu.:77.00  
 Max.   :206.00   Max.   :95.00   Max.   :97.00   Max.   :97.00  
  acousticness   instrumentalness    liveness      speechiness   
 Min.   : 0.00   Min.   : 0.000   Min.   : 3.00   Min.   : 2.00  
 1st Qu.: 6.00   1st Qu.: 0.000   1st Qu.:10.00   1st Qu.: 4.00  
 Median :17.00   Median : 0.000   Median :12.00   Median : 6.00  
 Mean   :27.42   Mean   : 1.682   Mean   :18.12   Mean   :10.12  
 3rd Qu.:44.00   3rd Qu.: 0.000   3rd Qu.:23.00   3rd Qu.:11.00  
 Max.   :97.00   Max.   :91.000   Max.   :91.00   Max.   :64.00  
     mode.n          key.A             key.B            key.D        
 Min.   :0.000   Min.   :0.00000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.:0.000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median :1.000   Median :0.00000   Median :0.0000   Median :0.00000  
 Mean   :0.584   Mean   :0.08005   Mean   :0.0853   Mean   :0.08136  
 3rd Qu.:1.000   3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :1.000   Max.   :1.00000   Max.   :1.0000   Max.   :1.00000  
     key.E             key.F             key.G            key.CS      
 Min.   :0.00000   Min.   :0.00000   Min.   :0.0000   Min.   :0.0000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.0000  
 Median :0.00000   Median :0.00000   Median :0.0000   Median :0.0000  
 Mean   :0.06693   Mean   :0.09055   Mean   :0.1076   Mean   :0.2205  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.0000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.0000   Max.   :1.0000  
     key.FS            key.GS            key.AS            key.DS       
 Min.   :0.00000   Min.   :0.00000   Min.   :0.00000   Min.   :0.00000  
 1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000   1st Qu.:0.00000  
 Median :0.00000   Median :0.00000   Median :0.00000   Median :0.00000  
 Mean   :0.08399   Mean   :0.09055   Mean   :0.05643   Mean   :0.03675  
 3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000   3rd Qu.:0.00000  
 Max.   :1.00000   Max.   :1.00000   Max.   :1.00000   Max.   :1.00000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#this time I'll separate target variable on a different object because I feel will be easier to handle</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>stream.train <span class="ot">&lt;-</span> train.n<span class="sc">$</span>streams</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Now will exclude streams from the dataset and predicted values from linear regression</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>train.n2 <span class="ot">&lt;-</span> train.n <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>streams)</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll scale train features</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>xtrain.n2.scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(train.n2)</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll scale also streams just to used in the cross validation. I rather use scaling as it keeps the distribution</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>y.train.n2.scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(stream.train)</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll create the lambda sequence value </span></span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a>lambda.array <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from=</span><span class="fl">0.1</span>, <span class="at">to=</span> <span class="dv">100</span>, <span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a><span class="co">#Cross validation using cv.glmnet</span></span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a>cv.lasso.model <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(xtrain.n2.scaled, y.train.n2.scaled, <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">lambda=</span>lambda.array)</span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cv.lasso.model, <span class="at">xvar =</span> <span class="st">'lambda'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.window(...): "xvar" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): "xvar" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in axis(side = side, at = at, labels = labels, ...): "xvar" is not a
graphical parameter

Warning in axis(side = side, at = at, labels = labels, ...): "xvar" is not a
graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in box(...): "xvar" is not a graphical parameter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in title(...): "xvar" is not a graphical parameter</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#getting the best lambda</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>best.lasso.lambda <span class="ot">&lt;-</span> cv.lasso.model<span class="sc">$</span>lambda.min</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>best.lasso.lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#MSE</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>mean.lasso.error <span class="ot">&lt;-</span> <span class="fu">mean</span>(cv.lasso.model<span class="sc">$</span>cvm)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mean.lasso.error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9984841</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">coef</span>(cv.lasso.model))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>32 x 1 sparse Matrix of class "dgCMatrix"
                               s1
(Intercept)          3.050052e-17
number.art.song      .           
released_year        .           
released_month       .           
released_day         .           
in_spotify_playlists 4.395318e-01
in_spotify_charts    .           
in_apple_playlists   3.224483e-01
in_apple_charts      .           
in_deezer_playlists  5.549454e-02
in_deezer_charts     .           
in_shazam_charts     .           
bpm                  .           
danceability         .           
valence              .           
energy               .           
acousticness         .           
instrumentalness     .           
liveness             .           
speechiness          .           
mode.n               .           
key.A                .           
key.B                .           
key.D                .           
key.E                .           
key.F                .           
key.G                .           
key.CS               .           
key.FS               .           
key.GS               .           
key.AS               .           
key.DS               .           </code></pre>
</div>
</div>
<p>Interesting to see that Lasso model keeps the presence of the song in playlist on the 3 main streaming platforms.</p>
</section>
<section id="method-3---random-forest" class="level3">
<h3 class="anchored" data-anchor-id="method-3---random-forest">Method 3 - Random Forest</h3>
<p>Lastly, I’ll use random forest and this time I’ll use the class.deciles created previously to use it as classification.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First I'll bring back as a separate object the class.deciles variable</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>train.n2<span class="sc">$</span>class.decile <span class="ot">&lt;-</span> train<span class="sc">$</span>class.decile</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>train.n2<span class="sc">$</span>class.decile <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train.n2<span class="sc">$</span>class.decile)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tune the hyperparameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>tune_spec <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">trees =</span> <span class="fu">tune</span>(), <span class="at">mtry =</span> <span class="fu">tune</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co">#starting with this values</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>rf_grid <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">trees</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">800</span>)),</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mtry</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">31</span>)),</span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">5</span>)</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1977</span>)</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train.n2, <span class="at">v =</span> <span class="dv">5</span>)</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>rf_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(tune_spec) <span class="sc">%&gt;%</span></span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_formula</span>(class.decile <span class="sc">~</span> .)</span>
<span id="cb80-18"><a href="#cb80-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-19"><a href="#cb80-19" aria-hidden="true" tabindex="-1"></a><span class="co">#For the purpose to train the model I'll use F1 as metric, despite I'll use mdae for measuring performance later</span></span>
<span id="cb80-20"><a href="#cb80-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-21"><a href="#cb80-21" aria-hidden="true" tabindex="-1"></a>my_metrics <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(f_meas)</span>
<span id="cb80-22"><a href="#cb80-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-23"><a href="#cb80-23" aria-hidden="true" tabindex="-1"></a>rf_res <span class="ot">&lt;-</span> </span>
<span id="cb80-24"><a href="#cb80-24" aria-hidden="true" tabindex="-1"></a>  rf_wf <span class="sc">%&gt;%</span> </span>
<span id="cb80-25"><a href="#cb80-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(<span class="at">resamples =</span> folds, <span class="at">grid =</span> rf_grid, <span class="at">metrics =</span> my_metrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Visualize the results and best parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>rf_res <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>() <span class="sc">%&gt;%</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"f_meas"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mtry, trees, mean) <span class="sc">%&gt;%</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(mtry, trees, <span class="at">fill =</span> mean)) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_tile</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Best Parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>best_params <span class="ot">&lt;-</span> rf_res <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="st">"f_meas"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>best_params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mtry trees .config              
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;                
1    31   275 Preprocessor1_Model22</code></pre>
</div>
</div>
<p>Explore a different region</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Now with this values</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>rf_grid2 <span class="ot">&lt;-</span> <span class="fu">grid_regular</span>(</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">trees</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">500</span>)),</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mtry</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">31</span>)),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="dv">5</span>)</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1979</span>)</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>folds2 <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train.n2, <span class="at">v =</span> <span class="dv">10</span>)</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>rf_res2 <span class="ot">&lt;-</span> </span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>  rf_wf <span class="sc">%&gt;%</span> </span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(<span class="at">resamples =</span> folds2, <span class="at">grid =</span> rf_grid2, <span class="at">metrics =</span> my_metrics)</span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>rf_res2 <span class="sc">%&gt;%</span></span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">collect_metrics</span>() <span class="sc">%&gt;%</span></span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.metric <span class="sc">==</span> <span class="st">"f_meas"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(mtry, trees, mean) <span class="sc">%&gt;%</span></span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(mtry, trees, <span class="at">fill =</span> mean)) <span class="sc">+</span></span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_tile</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>best_params2 <span class="ot">&lt;-</span> rf_res2 <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_best</span>(<span class="st">"f_meas"</span>)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>best_params2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
   mtry trees .config              
  &lt;int&gt; &lt;int&gt; &lt;chr&gt;                
1    10   300 Preprocessor1_Model03</code></pre>
</div>
</div>
</section>
</section>
<section id="section-4.2---choose-hyperparameters-fit-and-test-models" class="level2">
<h2 class="anchored" data-anchor-id="section-4.2---choose-hyperparameters-fit-and-test-models">Section 4.2 - Choose hyperparameters; fit and test models</h2>
<p>First I’ll make adjustments as training set, to the test set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  track_name        artist.name        number.art.song released_year 
 Length:191         Length:191         Min.   :1.000   Min.   :1957  
 Class :character   Class :character   1st Qu.:1.000   1st Qu.:2020  
 Mode  :character   Mode  :character   Median :1.000   Median :2022  
                                       Mean   :1.623   Mean   :2019  
                                       3rd Qu.:2.000   3rd Qu.:2022  
                                       Max.   :7.000   Max.   :2023  
                                                                     
 released_month    released_day   in_spotify_playlists in_spotify_charts
 Min.   : 1.000   Min.   : 1.00   Min.   :   86        Min.   : 0.00    
 1st Qu.: 3.000   1st Qu.: 6.00   1st Qu.: 1006        1st Qu.: 0.00    
 Median : 6.000   Median :14.00   Median : 2415        Median : 4.00    
 Mean   : 6.152   Mean   :14.22   Mean   : 5245        Mean   :12.59    
 3rd Qu.: 9.000   3rd Qu.:22.00   3rd Qu.: 5868        3rd Qu.:20.00    
 Max.   :12.000   Max.   :31.00   Max.   :43899        Max.   :83.00    
                                                                        
    streams          in_apple_playlists in_apple_charts  in_deezer_playlists
 Min.   :1.365e+06   Min.   :  0.00     Min.   :  0.00   Min.   :  0.0      
 1st Qu.:1.509e+08   1st Qu.: 13.00     1st Qu.:  8.00   1st Qu.: 14.0      
 Median :3.041e+08   Median : 32.00     Median : 39.00   Median : 39.0      
 Mean   :5.492e+08   Mean   : 74.66     Mean   : 49.09   Mean   :132.8      
 3rd Qu.:7.416e+08   3rd Qu.:107.00     3rd Qu.: 81.50   3rd Qu.:150.8      
 Max.   :3.704e+09   Max.   :672.00     Max.   :199.00   Max.   :965.0      
                                                         NA's   :13         
 in_deezer_charts in_shazam_charts      bpm            key           
 Min.   : 0.000   Min.   :  0.00   Min.   : 71.0   Length:191        
 1st Qu.: 0.000   1st Qu.:  0.00   1st Qu.:101.5   Class :character  
 Median : 0.000   Median :  3.00   Median :120.0   Mode  :character  
 Mean   : 3.115   Mean   : 43.64   Mean   :123.2                     
 3rd Qu.: 2.000   3rd Qu.: 34.75   3rd Qu.:141.0                     
 Max.   :45.000   Max.   :727.00   Max.   :206.0                     
                  NA's   :13                                         
     mode            danceability     valence          energy     
 Length:191         Min.   :25.0   Min.   : 4.00   Min.   :20.00  
 Class :character   1st Qu.:58.0   1st Qu.:35.00   1st Qu.:52.50  
 Mode  :character   Median :70.0   Median :52.00   Median :66.00  
                    Mean   :68.1   Mean   :51.15   Mean   :64.51  
                    3rd Qu.:79.0   3rd Qu.:68.00   3rd Qu.:76.50  
                    Max.   :96.0   Max.   :97.00   Max.   :97.00  
                                                                  
  acousticness   instrumentalness    liveness      speechiness   
 Min.   : 0.00   Min.   : 0.000   Min.   : 3.00   Min.   : 2.00  
 1st Qu.: 6.00   1st Qu.: 0.000   1st Qu.:10.00   1st Qu.: 4.00  
 Median :18.00   Median : 0.000   Median :13.00   Median : 6.00  
 Mean   :25.62   Mean   : 1.178   Mean   :18.59   Mean   :10.19  
 3rd Qu.:38.50   3rd Qu.: 0.000   3rd Qu.:25.50   3rd Qu.:13.50  
 Max.   :94.00   Max.   :51.000   Max.   :97.00   Max.   :45.00  
                                                                 
      id           
 Length:191        
 Class :character  
 Mode  :character  
                   
                   
                   
                   </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's review the character variables and create dummies that can be use later when building the models</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(test<span class="sc">$</span>key)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "F"  "G#" "B"  "D"  "G"  "A#" "E"  "C#" ""   "F#" "A"  "D#"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(test<span class="sc">$</span>mode)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Major" "Minor"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploring the frequency of the values in the key</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>key.table<span class="ot">&lt;-</span><span class="fu">table</span>(test<span class="sc">$</span>key)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>key.table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    A A#  B C#  D D#  E  F F#  G G# 
21 14 14 16 26 19  5 11 20  9 14 22 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#replacing blank cells with NA</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>test<span class="sc">$</span>key <span class="ot">&lt;-</span> <span class="fu">na_if</span>(test<span class="sc">$</span>key, <span class="st">''</span>)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a><span class="co">#replacing NA with the most frequent value in the feature, in this case C#</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(key), <span class="st">"C#"</span>, key))</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll create dummy for key and mode </span></span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mode.n =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a>        mode <span class="sc">==</span> <span class="st">"Major"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a>        mode <span class="sc">==</span> <span class="st">"Minor"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a>        ))<span class="sc">%&gt;%</span></span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.A =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"A"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-20"><a href="#cb95-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.B =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-21"><a href="#cb95-21" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"B"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-22"><a href="#cb95-22" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-23"><a href="#cb95-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.D =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-24"><a href="#cb95-24" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"D"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-25"><a href="#cb95-25" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-26"><a href="#cb95-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.E =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-27"><a href="#cb95-27" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"E"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-28"><a href="#cb95-28" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-29"><a href="#cb95-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.F =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-30"><a href="#cb95-30" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"F"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-31"><a href="#cb95-31" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-32"><a href="#cb95-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.G =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-33"><a href="#cb95-33" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"G"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-34"><a href="#cb95-34" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-35"><a href="#cb95-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.CS =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-36"><a href="#cb95-36" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"C#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-37"><a href="#cb95-37" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-38"><a href="#cb95-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.FS =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-39"><a href="#cb95-39" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"F#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-40"><a href="#cb95-40" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-41"><a href="#cb95-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.GS =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-42"><a href="#cb95-42" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"G#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-43"><a href="#cb95-43" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-44"><a href="#cb95-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.AS =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-45"><a href="#cb95-45" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"A#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-46"><a href="#cb95-46" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))<span class="sc">%&gt;%</span></span>
<span id="cb95-47"><a href="#cb95-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">key.DS =</span> <span class="fu">case_when</span>(</span>
<span id="cb95-48"><a href="#cb95-48" aria-hidden="true" tabindex="-1"></a>        key <span class="sc">==</span> <span class="st">"D#"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb95-49"><a href="#cb95-49" aria-hidden="true" tabindex="-1"></a>        <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb95-50"><a href="#cb95-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-51"><a href="#cb95-51" aria-hidden="true" tabindex="-1"></a><span class="co">#Lastly I'll replace the some NAs using median. For in_deezer_playlists, in_shazam_charts and stream</span></span>
<span id="cb95-52"><a href="#cb95-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-53"><a href="#cb95-53" aria-hidden="true" tabindex="-1"></a>median.deezer.playlist.ts <span class="ot">&lt;-</span> <span class="fu">median</span>(test<span class="sc">$</span>in_deezer_playlists, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb95-54"><a href="#cb95-54" aria-hidden="true" tabindex="-1"></a>median.shazam.chart.ts <span class="ot">&lt;-</span> <span class="fu">median</span>(test<span class="sc">$</span>in_shazam_charts, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb95-55"><a href="#cb95-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-56"><a href="#cb95-56" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> </span>
<span id="cb95-57"><a href="#cb95-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_deezer_playlists =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(in_deezer_playlists), median.deezer.playlist.t, in_deezer_playlists)) <span class="sc">%&gt;%</span></span>
<span id="cb95-58"><a href="#cb95-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">in_shazam_charts =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(in_shazam_charts), median.shazam.chart.t, in_shazam_charts))</span>
<span id="cb95-59"><a href="#cb95-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-60"><a href="#cb95-60" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's create the Decile variable based on the streams to use it later in classification method</span></span>
<span id="cb95-61"><a href="#cb95-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-62"><a href="#cb95-62" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">class.decile =</span> <span class="fu">ntile</span>(streams, <span class="dv">10</span>))</span>
<span id="cb95-63"><a href="#cb95-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-64"><a href="#cb95-64" aria-hidden="true" tabindex="-1"></a><span class="co">#now the dataset for testing, removing non-numeric or irrelevant variables</span></span>
<span id="cb95-65"><a href="#cb95-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-66"><a href="#cb95-66" aria-hidden="true" tabindex="-1"></a>test.n <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>track_name, <span class="sc">-</span>artist.name, <span class="sc">-</span>key, <span class="sc">-</span>mode, <span class="sc">-</span>id, <span class="sc">-</span>class.decile)</span>
<span id="cb95-67"><a href="#cb95-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-68"><a href="#cb95-68" aria-hidden="true" tabindex="-1"></a><span class="co">#extracting test actual streams </span></span>
<span id="cb95-69"><a href="#cb95-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-70"><a href="#cb95-70" aria-hidden="true" tabindex="-1"></a>stream.test <span class="ot">&lt;-</span> test.n<span class="sc">$</span>streams</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="linear-regression-fitting-and-testing" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-fitting-and-testing">Linear regression fitting and testing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions for new data</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>lm.predicted<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, test.n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(model1, test.n): prediction from rank-deficient fit;
attr(*, "non-estim") has doubtful cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>lm.predicted<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">predict</span>(model3, test.n)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking MdAE</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>mdae_lm1.final <span class="ot">&lt;-</span> <span class="fu">mdae</span>(stream.test, lm.predicted<span class="fl">.1</span>)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lm1.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 135837770</code></pre>
</div>
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>mdae_lm3.final <span class="ot">&lt;-</span> <span class="fu">mdae</span>(stream.test, lm.predicted<span class="fl">.3</span>)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lm3.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 123474556</code></pre>
</div>
</div>
</section>
<section id="lasso-regression-fitting-and-testing" class="level3">
<h3 class="anchored" data-anchor-id="lasso-regression-fitting-and-testing">Lasso Regression fitting and testing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Now will exclude streams from the dataset and predicted values from linear regression</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>test.n2 <span class="ot">&lt;-</span> test.n <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>streams)</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="co">#I'll scale test features</span></span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a>xtest.n2.scaled <span class="ot">&lt;-</span> <span class="fu">scale</span>(test.n2)</span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-9"><a href="#cb102-9" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model using the best lambda in lasso</span></span>
<span id="cb102-10"><a href="#cb102-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-11"><a href="#cb102-11" aria-hidden="true" tabindex="-1"></a>lasso.model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(xtest.n2.scaled, stream.test, <span class="at">alpha=</span><span class="dv">1</span>, <span class="at">lambda=</span>best.lasso.lambda)</span>
<span id="cb102-12"><a href="#cb102-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">coef</span>(lasso.model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>32 x 1 sparse Matrix of class "dgCMatrix"
                             s0
(Intercept)           549175763
number.art.song       -14064461
released_year         -28898388
released_month         15279704
released_day           11015034
in_spotify_playlists  226034156
in_spotify_charts     151290594
in_apple_playlists    249601103
in_apple_charts        21338444
in_deezer_playlists   114996405
in_deezer_charts      -69063564
in_shazam_charts     -126032019
bpm                    -3506104
danceability          -47405242
valence                -7346601
energy                -18401617
acousticness          -17181614
instrumentalness        7630502
liveness               14395334
speechiness            -4810544
mode.n                -13167404
key.A                 -12077321
key.B                   5200964
key.D                   5981359
key.E                   6473279
key.F                  17801687
key.G                 -21177792
key.CS                 -4135984
key.FS                 24496493
key.GS                -19115050
key.AS                  1662262
key.DS                 11780702</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict streams in test set</span></span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>ytest.lasso.pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lasso.model, <span class="at">newx =</span> xtest.n2.scaled, <span class="at">penalty =</span> best.lasso.lambda)</span>
<span id="cb104-4"><a href="#cb104-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-5"><a href="#cb104-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb104-6"><a href="#cb104-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Checking MdAE</span></span>
<span id="cb104-7"><a href="#cb104-7" aria-hidden="true" tabindex="-1"></a>mdae_lasso.final <span class="ot">&lt;-</span> <span class="fu">mdae</span>(stream.test, ytest.lasso.pred)</span>
<span id="cb104-8"><a href="#cb104-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_lasso.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 113556904</code></pre>
</div>
</div>
</section>
<section id="random-forest-fitting-and-testing" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-fitting-and-testing">Random Forest fitting and testing</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First I need to bring back class.decile for the test set</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>test.n2<span class="sc">$</span>class.decile <span class="ot">&lt;-</span> test<span class="sc">$</span>class.decile</span>
<span id="cb106-4"><a href="#cb106-4" aria-hidden="true" tabindex="-1"></a>test.n2<span class="sc">$</span>class.decile <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(test.n2<span class="sc">$</span>class.decile)</span>
<span id="cb106-5"><a href="#cb106-5" aria-hidden="true" tabindex="-1"></a>test.class <span class="ot">&lt;-</span> test.n2<span class="sc">$</span>class.decile</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Will first check model 1 (mtry=31 and trees=275)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model 1</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>rf1 <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">mtry=</span><span class="dv">31</span>, <span class="at">trees=</span><span class="dv">275</span>) <span class="sc">%&gt;%</span></span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a>rf_fit1 <span class="ot">&lt;-</span> rf1 <span class="sc">%&gt;%</span></span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(class.decile <span class="sc">~</span> ., <span class="at">data =</span> test.n2)</span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict on the test set using first parameters:</span></span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>test_pred1 <span class="ot">&lt;-</span>  rf_fit1 <span class="sc">%&gt;%</span></span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(test.n2) <span class="sc">%&gt;%</span></span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test.n2) <span class="sc">%&gt;%</span></span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(class.decile, .pred_class)</span>
<span id="cb107-17"><a href="#cb107-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-18"><a href="#cb107-18" aria-hidden="true" tabindex="-1"></a>test_pred1 <span class="sc">%&gt;%</span></span>
<span id="cb107-19"><a href="#cb107-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">my_metrics</span>(<span class="at">truth =</span> class.decile, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 f_meas  macro          0.995</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Transforming to numeric to be able to calculate mdae</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>rf1.pred <span class="ot">&lt;-</span> test_pred1<span class="sc">$</span>.pred_class</span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>rf1.pred <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(rf1.pred)</span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>test.class.n <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test.class)</span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's see the consufion matrix</span></span>
<span id="cb109-8"><a href="#cb109-8" aria-hidden="true" tabindex="-1"></a>confusion_matrix1 <span class="ot">&lt;-</span> <span class="fu">table</span>(test.class.n, rf1.pred)</span>
<span id="cb109-9"><a href="#cb109-9" aria-hidden="true" tabindex="-1"></a>confusion_matrix1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            rf1.pred
test.class.n  1  2  3  4  5  6  7  8  9 10
          1  20  0  0  0  0  0  0  0  0  0
          2   0 19  0  0  0  0  0  0  0  0
          3   0  0 19  0  0  0  0  0  0  0
          4   0  0  0 19  0  0  0  0  0  0
          5   0  0  0  0 18  0  0  0  1  0
          6   0  0  0  0  0 19  0  0  0  0
          7   0  0  0  0  0  0 19  0  0  0
          8   0  0  0  0  0  0  0 19  0  0
          9   0  0  0  0  0  0  0  0 19  0
          10  0  0  0  0  0  0  0  0  0 19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Median Absolute Error</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>mdae_rf1.final <span class="ot">&lt;-</span> <span class="fu">mdae</span>(test.class.n, rf1.pred)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_rf1.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>It is important to mention that Median Absolute Error is not the ideal metric for Random Forest performance, it is more common using Accuracy, F1 Score, Precision, ROC AUC, Recall, etc. MdAE is more appropiate for regression type of method (instead of classification), however if I need to use the same metric for all methods, MdAE is feasible.</p>
<p>Now model 2 (mtry=10 and trees=300)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co">#fit the model 2</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>rf2 <span class="ot">&lt;-</span> <span class="fu">rand_forest</span>(<span class="at">mtry=</span><span class="dv">10</span>, <span class="at">trees=</span><span class="dv">300</span>) <span class="sc">%&gt;%</span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>rf_fit2 <span class="ot">&lt;-</span> rf2 <span class="sc">%&gt;%</span></span>
<span id="cb113-9"><a href="#cb113-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(class.decile <span class="sc">~</span> ., <span class="at">data =</span> test.n2)</span>
<span id="cb113-10"><a href="#cb113-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-11"><a href="#cb113-11" aria-hidden="true" tabindex="-1"></a><span class="co">#Predict on the test set using first parameters:</span></span>
<span id="cb113-12"><a href="#cb113-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-13"><a href="#cb113-13" aria-hidden="true" tabindex="-1"></a>test_pred2 <span class="ot">&lt;-</span>  rf_fit2 <span class="sc">%&gt;%</span></span>
<span id="cb113-14"><a href="#cb113-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">predict</span>(test.n2) <span class="sc">%&gt;%</span></span>
<span id="cb113-15"><a href="#cb113-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(test.n2) <span class="sc">%&gt;%</span></span>
<span id="cb113-16"><a href="#cb113-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(class.decile, .pred_class)</span>
<span id="cb113-17"><a href="#cb113-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-18"><a href="#cb113-18" aria-hidden="true" tabindex="-1"></a>test_pred2 <span class="sc">%&gt;%</span></span>
<span id="cb113-19"><a href="#cb113-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">my_metrics</span>(<span class="at">truth =</span> class.decile, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 f_meas  macro          0.990</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>rf2.pred2 <span class="ot">&lt;-</span> test_pred2<span class="sc">$</span>.pred_class</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>rf2.pred2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(rf2.pred2)</span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>test.class.n2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(test.class)</span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's see the consufion matrix</span></span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>confusion_matrix2 <span class="ot">&lt;-</span> <span class="fu">table</span>(test.class.n, rf2.pred2)</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>confusion_matrix2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            rf2.pred2
test.class.n  1  2  3  4  5  6  7  8  9 10
          1  20  0  0  0  0  0  0  0  0  0
          2   0 19  0  0  0  0  0  0  0  0
          3   0  0 19  0  0  0  0  0  0  0
          4   0  0  0 19  0  0  0  0  0  0
          5   0  0  0  0 18  0  0  0  1  0
          6   0  0  0  0  0 18  0  0  1  0
          7   0  0  0  0  0  0 19  0  0  0
          8   0  0  0  0  0  0  0 19  0  0
          9   0  0  0  0  0  0  0  0 19  0
          10  0  0  0  0  0  0  0  0  0 19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Median Absolute Error</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>mdae_rf2.final <span class="ot">&lt;-</span> <span class="fu">mdae</span>(test.class.n, rf2.pred2)</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mdae_rf2.final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="section-6---compare-models" class="level1">
<h1>Section 6 - Compare models</h1>
<p>Compare and evaluate the models in terms of overfitting vs underfitting, bias vs variance tradeoff, flexibility vs interpretability.</p>
<p>Here a summary of the Median Absolute Errors for each model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example objects</span></span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>MdAE_Linear_Regression_Model_1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">135968120</span>)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>MdAE_Linear_Regression_Model_3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">123474556</span>)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>MdAE_Lasso <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">113643028</span>)</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>MdAE_RF_1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>)</span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>MdAE_RF_2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>)</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame</span></span>
<span id="cb119-10"><a href="#cb119-10" aria-hidden="true" tabindex="-1"></a>models.table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">"MdAE Linear Regression Model1"</span> <span class="ot">=</span> MdAE_Linear_Regression_Model_1, <span class="st">"MdAE Linear Regression Model3"</span> <span class="ot">=</span> MdAE_Linear_Regression_Model_3, <span class="st">"MdAE Lasso"</span> <span class="ot">=</span> MdAE_Lasso, <span class="st">"MdAE RF1"</span> <span class="ot">=</span> MdAE_RF_1, <span class="st">"MdAE RF2"</span> <span class="ot">=</span> MdAE_RF_2)</span>
<span id="cb119-11"><a href="#cb119-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-12"><a href="#cb119-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the data frame with kable</span></span>
<span id="cb119-13"><a href="#cb119-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(models.table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  MdAE.Linear.Regression.Model1 MdAE.Linear.Regression.Model3 MdAE.Lasso
1                     135968120                     123474556  113643028
  MdAE.RF1 MdAE.RF2
1        0        0</code></pre>
</div>
</div>
<p>The first thing to note here is that the absolute error in the hundred millions seems high to me, overall the variables in the different models while explain a good proportion of the number of streams the performance doesn’s seems the best to me.</p>
<p>The above statement seems not applying to the Random Forest method which has a zero error but this could mean a overfitting, even trying different hyperparameters it ended in almost zero error. Perhaps when classifying the number streams in 10 categories based on deciles of the distribution facilitate the prediction. Still it does sound like a overfitting.</p>
<p>Then linear regression and lasso a more balanced model, with a more “reasonable” error iwhile high, and offers better interpretability by simplifying the model.</p>
<p>Then among linear and lasso regression, seems that Linear Model 3 offer a good model in terms of simplicity and performance compared to linear model 1 (lower error and less predictors).</p>
<p>Lasso seems to offers a lot more interpretability without being too much underfitting. This model uses only 3 main variables and have the lowest Median Absolute Error (besides Random Forest). However even though doesn’t seems underfitting too much (by judging for the MdAE), it can be too simple so maybe it can imply biased model.</p>
</section>
<section id="section-7---ethical-implications" class="level1">
<h1>Section 7 - Ethical implications</h1>
<p>In the case of this model and what I have been trying to do which is predict number of songs streams, and based on the features collected in this dataset (nothing seems too personal in te data collected), I don’t see a big ethical risks here.</p>
<p>However, as all the marketing research analysis, at the end, it may result on manipulation of the user to generate more engagement in the platform which at the end is probably the end goal of music streaming platforms: more engagement for the users to spend more time in the platform.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>